### ISSUE TITLE
next,electron error tips: window is not defined

### ISSUE THREAD

**Issue by luokunman** [katspaugh/wavesurfer.js#2571] opened 2022-08-24 04:02 UTC
### Code needed to reproduce the issue:
quote code
```
/// child.tsx
import WaveSurfer from 'wavesurfer.js'
import MicrophonePlugin from 'wavesurfer.js/src/plugin/microphone';

const wavesurfer = WaveSurfer?.create({
  container: '#audioChart',//容器
  waveColor     : 'black',
  interact      : false,
  cursorWidth   : 0,
  plugins: [
    MicrophonePlugin.create({}),
  ]
});
wavesurfer.microphone.on('deviceReady', function(stream) {
  console.log('Device ready!', stream);
});
wavesurfer.microphone.on('deviceError', function(code) {
  console.warn('Device error: ' + code);
});
// start the microphone
wavesurfer.microphone.start();


/// parent.tsx
import dynamic from 'next/dynamic'

const Child = dynamic(
  import('./child'),
  {
    ssr: false   //这个要加上,禁止使用 SSR
  }
)

export default () => <Child />
```

error code
```
var _default = (window && window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || window.oRequestAnimationFrame || window.msRequestAnimationFrame || function (callback, element) {
  return setTimeout(callback, 1000 / 60);
}).bind(window);
```
error tips

window is not defined
    at Object../src/util/request-animation-frame.js (/Users/company/JZRecordForMac/node_modules/_wavesurfer.js@6.2.0@wavesurfer.js/dist/wavesurfer.js:3519:16)
    at __webpack_require__ (/Users/company/JZRecordForMac/node_modules/_wavesurfer.js@6.2.0@wavesurfer.js/dist/wavesurfer.js:6639:41)
    at Object../src/util/index.js (/Users/company/JZRecordForMac/node_modules/_wavesurfer.js@6.2.0@wavesurfer.js/dist/wavesurfer.js:3054:53)
    at __webpack_require__ (/Users/company/JZRecordForMac/node_modules/_wavesurfer.js@6.2.0@wavesurfer.js/dist/wavesurfer.js:6639:41)
    at Object../src/wavesurfer.js (/Users/company/JZRecordForMac/node_modules/_wavesurfer.js@6.2.0@wavesurfer.js/dist/wavesurfer.js:3629:36)
    at __webpack_require__ (/Users/company/JZRecordForMac/node_modules/_wavesurfer.js@6.2.0@wavesurfer.js/dist/wavesurfer.js:6639:41)
    at /Users/company/JZRecordForMac/node_modules/_wavesurfer.js@6.2.0@wavesurfer.js/dist/wavesurfer.js:6650:37
    at /Users/company/JZRecordForMac/node_modules/_wavesurfer.js@6.2.0@wavesurfer.js/dist/wavesurfer.js:6653:12
    at webpackUniversalModuleDefinition (/Users/company/JZRecordForMac/node_modules/_wavesurfer.js@6.2.0@wavesurfer.js/dist/wavesurfer.js:9:20)
    at Object.<anonymous> (/Users/company/JZRecordForMac/node_modules/_wavesurfer.js@6.2.0@wavesurfer.js/dist/wavesurfer.js:16:3)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)

**Comment by thijstriemstra** [comment] 2022-08-26 18:29
Duplicate of #1941

**Closed** 2023-01-25 10:05 UTC
Labels: plugins
