### ISSUE TITLE
skipForward() and skipBackward() are firing play() method also.

### ISSUE THREAD

**Issue by GigaMick** [katspaugh/wavesurfer.js#2189] opened 2021-02-17 20:31 UTC
I have some code that updates a counter inside 

```
    wavesurfer.on('play', function () {
// My code
})
```

However this same code is triggered whenever I click on the buttons that fire 

skipForward() and skipBackward().

I have also tried using skip(offset) and it also fires the code inside play().

Is there anything that can be done?

Thanks

**Comment by thijstriemstra** [comment] 2021-02-18 12:59
This looks like a duplicate of #636

**Comment by GigaMick** [comment] 2021-02-18 15:09
> This looks like a duplicate of #636

Thanks, I've replied over there now.

**Closed** 2021-02-18 15:18 UTC
Labels: duplicate

**Comment by sundayz** [comment] 2021-02-18 16:23
Use the click handler of your play button as a workaround. 

The last time we tried to remove the calls to play() and pause() it introduced new issues and we had to revert it: https://github.com/katspaugh/wavesurfer.js/pull/2151

**Comment by GigaMick** [comment] 2021-02-18 20:02
> Use the click handler of your play button as a workaround.
> 
> The last time we tried to remove the calls to play() and pause() it introduced new issues and we had to revert it: #2151

Thanks do you mean using 

```
<button id="playbutton" onclick="doSomething()"></button>
```

Thanks

**Comment by sundayz** [comment] 2021-02-18 20:03
Yes, something like that will work
