### ISSUE TITLE
The AudioContext was not allowed to start

### ISSUE THREAD

**Issue by mmasomi73** [katspaugh/wavesurfer.js#1657] opened 2019-05-24 06:27 UTC
Hi 

i tired really :(
i see #1531 & #1560

Examples is work correct without Error, But my samples not working, in issues not explain how fix this problem

**Comment by mmasomi73** [comment] 2019-05-24 06:28
it's my sample: http://play.mmasomi.ir/

**Comment by thijstriemstra** [comment] 2019-05-24 18:47
@mmasomi73 what browser, what operating system, what wavesurfer.js version etc

**Comment by mmasomi73** [comment] 2019-05-24 19:35
any supported browser such as _chrome v.74_ 
_wavesurfer.js 2.2.1_
in local system is ok but when put on host not work

please help me, how fix them?

**Comment by mmasomi73** [comment] 2019-05-24 20:05
all my code: [https://github.com/mmasomi73/player](https://github.com/mmasomi73/player)

**Comment by thijstriemstra** [comment] 2019-05-25 00:23
you need to call `wavesurfer.backend.ac.resume()` in a button click to work around the autoplay restrictions in chrome i think.

**Comment by mmasomi73** [comment] 2019-05-25 01:29
thanks, i use that but not working

when i use `<audio>` tag and play once with `<audio>` tag and after reload page is work
and every time reload page show download audio alert

**Comment by moussaeltayeb** [comment] 2019-06-03 06:43
Have the same problem. `wavesurfer.backend.ac.resume()` does not remove the warning. In addition to that, it does play on safari for iOS, but without any sound. You can try the example at the home page of [https://wavesurfer-js.org](https://wavesurfer-js.org)

**Comment by thijstriemstra** [comment] 2019-06-05 08:38
> wavesurfer.backend.ac.resume() does not remove the warning

try creating a new audio context in a button click handler, and then create wavesurfer instance and pass in that audio context.

**Comment by thijstriemstra** [comment] 2019-07-10 21:50
Marking this as a duplicate of #1531.

**Closed by thijstriemstra** 2019-07-10 21:50 UTC
Labels: duplicate, question
