### ISSUE TITLE
Media Element and iOS

### ISSUE THREAD

**Issue by arian1123** [katspaugh/wavesurfer.js#543] opened 2015-10-06 15:49 UTC
Fantastic library btw! 
So Im using AJAX to create instances of the wavesurfer class through an AJAX request and loading the file as a MediaElement. This is works extremely well on computers and Android phones, however it does not fully work on iOS. When loading the page in iOS the waveforms dont display, and then only fade in when I click my play button. I tried locating where things are going wrong and it seems to me that the function basically pauses as it hits the .init() function. For whatever reason it responds properly when clicking play or trying to play a different track that I have already loaded. Is there a known bug for something like this? I know that on wavesurfer-js.org the waveform initializes fine, and in trying to reverse engineer I cannot find why my instances dont seem to initialize without clicking play. 
Any help here would be really appreciated! Thanks

EDIT: So I tried changing the MediaElement to WebAudio and it initialized as needed. There are other issues with WebAudio working properly, but is there any history of issues like this being tied to MediaElement?

**Comment by katspaugh** [comment] 2015-10-07 08:29
Duplicate of #509

**Comment by arian1123** [comment] 2015-10-07 14:20
@katspaugh read that thread already, my issue relates directly to rendering of the waveforms, not actually playing them. As mentions renders with WebAudio not MediaElement. Or am I missing something here.

**Comment by katspaugh** [comment] 2015-10-07 14:39
It's something different then, sorry.

**Comment by thijstriemstra** [comment] 2015-10-07 18:43
Ok. What browser and version of ios/wavesurfer were you using?

**Comment by arian1123** [comment] 2015-10-07 18:45
iOS 9, also tried on 8, with the newest version of Safari. Im using the last version uploaded of the wavesurfer.min.js file. Thanks

**Comment by arian1123** [comment] 2015-10-07 18:47
As mentioned before the strange part is that the wavesurfer object only seems to initalize (or trigger the 'ready' event) when I click play when using MediaElement, which makes little sense to me. It renders fine without needing to click play using WebAudio, however this is suboptimal since obviously it wont load files as quick as using MediaElement.

**Comment by thijstriemstra** [comment] 2015-10-07 18:48
The need to click to play is expected on iOS  isn't it?

**Comment by arian1123** [comment] 2015-10-07 18:51
From reading previous threads that what Im not sure about. I dont want the track to start playing when I load the page. I simply want it to display the waveform. Is clicking play needed to do that? Also if it is, would you know a workaround for example to would allow me to create a mimicked image of the waveform as placeholder? Thanks

**Comment by thijstriemstra** [comment] 2015-10-07 19:06
No clicking isn't needed to do that, true.

**Comment by arian1123** [comment] 2015-10-07 19:10
Right so whats happening is I need to click to for the waveforms to load. It will start playing as normal but basically it needs to start playing for it show the waveform. I added console output as well in the "ready" event and that only output when I clicked play. So basically there is some link to the event ready and play when using MediaElement. Any thoughts?

**Comment by therewasaguy** [comment] 2016-06-09 06:37
I ran into this issue and my fix was to tell the HTML5 media element to  `.load()`. Otherwise, iOS waits for a user event to trigger the loading necessary for playback, and `ready` only fires once enough frames have loaded for playback to begin. Wavesurfer is waiting for the ready event before it draws the waveform

**Comment by thijstriemstra** [comment] 2016-08-29 23:29
Can this be closed?

**Closed** 2016-11-13 12:05 UTC
