### ISSUE TITLE
Does not work in Edge at all

### ISSUE THREAD

**Issue by mahish** [katspaugh/wavesurfer.js#1761] opened 2019-10-04 07:14 UTC
![obrazek](https://user-images.githubusercontent.com/3687943/66187365-ea26e580-e684-11e9-8868-c43da30d7ecc.png)

### Wavesurfer.js version(s): 
v3.1.0

### Browser and operating system version(s): 
Edge 18, Windows 10

### Code needed to reproduce the issue: 
Go to https://wavesurfer-js.org/ in Edge

### Use behaviour needed to reproduce the issue: 
Check the player in the header and try to play it. Neither waveform or sound works. I do not get any errors in console.

**Comment by thijstriemstra** [comment] 2019-10-06 11:58
that's weird because Edge has WebAudio support right: https://blogs.windows.com/msedgedev/2015/05/19/bringing-web-audio-to-microsoft-edge-for-interoperable-gaming-and-enthusiast-media/

**Comment by mahish** [comment] 2019-10-08 13:32
@thijstriemstra … can you confirm the bug? I tested on two different Windows computers (same spec tho).

**Comment by trevasco** [comment] 2019-10-09 20:52
not working in Edge confirmed

**Comment by Bopser** [comment] 2019-10-19 18:42
Confirmed.Found following Error in Edge;
Microsoft Edge 44.18362.387.0
Microsoft EdgeHTML 18.18362

Tree on pic not full expanded !

![Error_Edge](https://user-images.githubusercontent.com/30476325/67149858-cbddfe00-f2b0-11e9-839e-78d0530cef3a.png)

**Comment by Bopser** [comment] 2019-10-19 19:18
supplement to the previous entry:
used:
    <script src="https://unpkg.com/wavesurfer.js/dist/wavesurfer.min.js"></script>
Error Pic is from my site in which i used code parts from the following playlist example :

https://wavesurfer-js.org/example/playlist/index.html

I just tried the original playlist example in Edge. This one doesn't work either.

**Comment by martinratinaud** [comment] 2019-12-24 07:03
@Bopser I agree that it does not work

It seems to come from this line
```
return new Response(new ReadableStream(new ProgressHandler(instance, contentLength, response)), fetchOptions);
``` in `wavesurfer.js`

But I haven't found a solution yet. Have you ?

**Comment by martinratinaud** [comment] 2019-12-24 10:22
I made a (very) temporary patch because it's christmas :-) and I need to make it work NOW

So
Here is the commit on my fork https://github.com/cme-pro/wavesurfer.js/commit/601e9b584e94d172f0fd7a4821c366bf196c8b91

And you can use by 
```
rm -Rf node_modules/wavesurfer.js &&  yarn add cme-pro/wavesurfer.js#fix/edge
```

I'm still interested to launch a PR if someone knows what is wrong with ReadableStream on Edge being here but not functional

Merry christmas to all of you

**Comment by thijstriemstra** [comment] 2019-12-24 19:14
thanks for the feedback @martinratinaud. Maybe take a look at https://stackoverflow.com/questions/55294816/how-do-i-create-a-readablestream-in-microsoft-edge and https://github.com/mapbox/mapbox-gl-js/commit/c49dd3151c9e9e528e6eec339f54e033cd190e29

**Comment by thijstriemstra** [comment] 2020-01-09 12:43
@martinratinaud can you make a pull request for your workaround?

**Comment by martinratinaud** [comment] 2020-01-13 04:26
@thijstriemstra sure I can but maybe you should validate the commit first https://github.com/cme-pro/wavesurfer.js/commit/601e9b584e94d172f0fd7a4821c366bf196c8b91 as
- I wrote no tests
- it downgrades the use of the progress indicator

**Comment by Kucziii** [comment] 2020-02-10 06:29
Hey! @thijstriemstra is it possibly going to be merged to master soon? We're having the same issue and currently we're using @martinratinaud fix as a workaround.
Just wanted to let you know it's working properly.

Thanks for your work!

**Comment by thijstriemstra** [comment] 2020-02-10 12:28
> is it possibly going to be merged to master soon? 

there is no pull request to merge. can you make one @Kucziii?

**Comment by gmpetrov** [comment] 2020-07-27 07:38
Any news for a fix with Edge browser ?

**Comment by dktsudgg** [comment] 2020-09-23 09:58
I was stucked with same problem, but I think this is done well after Edge Browser update.

**Comment by entonbiba** [comment] 2021-01-26 00:58
Working with latest version in both edge and edge chrome. reopen if needed.

![image](https://user-images.githubusercontent.com/5193884/105784789-77abda00-5f47-11eb-91b9-de8300f8b8eb.png)

![image](https://user-images.githubusercontent.com/5193884/105784770-6f539f00-5f47-11eb-9b2a-1faeab5fb20e.png)

![image](https://user-images.githubusercontent.com/5193884/105784877-acb82c80-5f47-11eb-8dcf-65fabfcfe024.png)

**Closed by entonbiba** 2021-01-26 00:58 UTC
Labels: bug
