### ISSUE TITLE
Region selction mobile dragging is not working

### ISSUE THREAD

**Issue by pradeep07us** [katspaugh/wavesurfer.js#695] opened 2016-04-07 11:56 UTC
Hi there... I am trying to use this in mobile view, but region dragging is not working it just create new region if it is enabled or if not then seek to that position.
Thank You

**Comment by chinshr** [comment] 2016-04-07 14:11
I see the same issue. It's a regression, it has worked before.

**Comment by katspaugh** [comment] 2016-04-07 15:00
@chinshr only in WebView?

**Comment by chinshr** [comment] 2016-04-07 15:23
I could reproduce it on mobile safari.

**Comment by pradeep07us** [comment] 2016-04-13 11:12
Any updates?

**Comment by katspaugh** [comment] 2016-11-11 16:06
This is fixed in the current version in either 5bf2e44a64e9618efc73be41be41f94b884fa820 or ee4fafe66a345ef22c0ddc3ebeaa6df8f3c0522c.

I cannot reproduce this bug on https://wavesurfer-js.org/plugins/regions.html anymore.

**Closed by katspaugh** 2016-11-11 16:06 UTC
Labels: bug
