### ISSUE TITLE
Spectrogram looks different between wavesurfer.js 5.2.0 and wavesurfer.js 6.0.1

### ISSUE THREAD

**Issue by mINgthub** [katspaugh/wavesurfer.js#2455] opened 2022-02-20 07:25 UTC
# wavesurfer.js 5.2.0
![image](https://user-images.githubusercontent.com/74526876/154832678-ef42ab74-191d-49c8-9700-f5f6c9c00741.png)
# wavesurfer.js 6.0.1
![image](https://user-images.githubusercontent.com/74526876/154832729-7b7fb62b-ad0e-491e-9c07-227efc6d162c.png)
Spectrogram looks small
# code
```js
var SpectrogramPlugin = window.WaveSurfer.spectrogram;
var wavesurfer = WaveSurfer.create({
    container: '#waveform',
    waveColor: 'violet',
    progressColor: 'purple',
    backgroundColor: 'rgba(0,0,0,.8)',
    pixelRatio: 1,
    plugins: [
        SpectrogramPlugin.create({
            container: '#spectrogram',
            fftSamples: 256
        })
    ]
    
})
var url = './audio.wav'
wavesurfer.load(url)
```

**Comment by thijstriemstra** [comment] 2022-02-20 19:01
Caused by changes in #2424

@dofuuz can you take a look at this? If we can't fix the new implementation I'm afraid it'll have to be reverted.

**Comment by dofuuz** [comment] 2022-02-21 01:18
Reverting #2424 is not a solution. Frequency label will be incorrect. And it will behavior differently with channel number.

As getting original samplerate is difficult, I suggest displaying spectrogram in 12kHz range by default. 
And making option for display range soon or later.
This will draw spectrogram looks like 5.2.0.

**Comment by mINgthub** [comment] 2022-02-21 07:48
Hi there, i cannot really find the parameter of setting the spectrogram in 12kHZ range by default, is any suggestion? Thank you.

**Comment by mINgthub** [comment] 2022-02-21 07:49
> Reverting #2424 is not a solution. Frequency label will be incorrect. And it will behavior differently with channel number.
> 
> As getting original samplerate is difficult, I suggest displaying spectrogram in 12kHz range by default. And making option for display range soon or later. This will draw spectrogram looks like 5.2.0.
Hi there, i cannot really find the parameter of setting the spectrogram in 12kHZ range by default, is any suggestion? Thank you.

**Comment by dofuuz** [comment] 2022-02-21 08:44
@mINgthub It's just a suggestion for future improvement, not has been implemented.

**Closed** 2022-03-05 19:19 UTC
Labels: plugins
