### ISSUE TITLE
Zooming in makes waveform disappear eventually

### ISSUE THREAD

**Issue by ffxsam** [katspaugh/wavesurfer.js#504] opened 2015-08-22 04:29 UTC
Any reason this would happen?

![licecap](https://cloud.githubusercontent.com/assets/12532733/9422539/b4db3254-484b-11e5-8723-f5834631f4af.gif)

**Comment by ffxsam** [comment] 2015-08-22 06:16
Ahh, when the width goes past about 30000px, it vanishes. :) I guess that's bad. Maybe there should be a hard limit that stops it from zooming at that point?

**Comment by katspaugh** [comment] 2015-08-22 09:59
Duplicate of #458.

**Closed by katspaugh** 2015-08-22 09:59 UTC
