### ISSUE TITLE
Using  responsive param created Cannot read property 'length' of null' error

### ISSUE THREAD

**Issue by sshadmand** [katspaugh/wavesurfer.js#1506] opened 2018-11-13 01:32 UTC
### Wavesurfer.js version(s):

```"wavesurfer.js": "^2.0.5",```

### Browser version(s):

Mac Chrome 70

### Code needed to reproduce the issue:
Using React, I load the below code. I noticed that the error only occurs with `responsive: true`. Commenting it out works cleanly.

```
this.wavesurfer = WaveSurfer.create({
        container: this.el,
        waveColor: color,
        progressColor: color,
        cursorColor: '#5173E7',
        cursorWidth: 3,
        barWidth: 1,
        responsive: true
        height,
        audioRate
      })
```

Error it produces in console
```
Uncaught TypeError: Cannot read property 'length' of null
    at t.value (wavesurfer.min.js:6)
    at t.value (wavesurfer.min.js:6)
    at wavesurfer.min.js:6
    at wavesurfer.min.js:6
    at Array.forEach (<anonymous>)
    at t.value (wavesurfer.min.js:6)
    at wavesurfer.min.js:6
    at n (wavesurfer.min.js:6)
    at wrapped (index.js:3221)
value @ wavesurfer.min.js:6
value @ wavesurfer.min.js:6
(anonymous) @ wavesurfer.min.js:6
(anonymous) @ wavesurfer.min.js:6
value @ wavesurfer.min.js:6
(anonymous) @ wavesurfer.min.js:6
n @ wavesurfer.min.js:6
wrapped @ index.js:3221
setTimeout (async)
(anonymous) @ index.js:3430
l @ wavesurfer.min.js:6
wrapped @ index.js:3221
```

**Comment by thijstriemstra** [comment] 2018-11-16 01:05
duplicate of #1507

**Closed by thijstriemstra** 2018-11-16 01:05 UTC
Labels: duplicate
