### ISSUE TITLE
Cursor not shown when waveColor and ProgressColor are the same

### ISSUE THREAD

**Issue by pkeuter** [katspaugh/wavesurfer.js#431] opened 2015-04-10 14:07 UTC
The play-cursor is not being shown when my waveColor and progressColor are the same value. It appears again when I change one of the colors a little bit (ie from #FFFFFF to #FFFFFE)

**Comment by thijstriemstra** [comment] 2015-04-10 15:31
Please go through list of existing tickets before opening a new one because this seems like a duplicate of #418..

**Comment by katspaugh** [comment] 2015-04-10 15:37
Yep, please watch #418.

**Closed by katspaugh** 2015-04-10 15:37 UTC
