### ISSUE TITLE
Pre-generated waveform on MultiCanvas and zoom doesn't fill out each canvas

### ISSUE THREAD

**Issue by moyara** [katspaugh/wavesurfer.js#814] opened 2016-08-31 20:49 UTC
Hi I'm using multicanvas and pre-generated waveform to deal with long audio file.
Below is the options

```
this.player = WaveSurfer.create({
      container: $element.selector,
      height: 100,
      cursorColor: 'red',
      backend: 'MediaElement',
      renderer: 'MultiCanvas'
    });

this.player.load(url, waveform);

this.player.on('ready', ()=>{
      this.player.zoom(20);
      this.setVolume(100);
    });
```

When it comes with multiple canvas, each wave doesn't stretch to its sub canvas.

<img width="1163" alt="2016-08-31 1 46 26" src="https://cloud.githubusercontent.com/assets/568994/18145761/5e0e0da8-6f81-11e6-930c-41ae775359ce.png">
<img width="1179" alt="2016-08-31 1 46 34" src="https://cloud.githubusercontent.com/assets/568994/18145762/5e118ea6-6f81-11e6-8d4b-e926090cb8f5.png">

It only happens with pre-generated waveform. It works fine if I load audio without waveform.
`this.player.load(url);`

**Comment by chrisparton1991** [comment] 2016-08-31 22:24
Hey @moyara, is there any chance I could get your pre-generated peak data for testing?

**Comment by moyara** [comment] 2016-08-31 22:42
Sure, this is the peak I used

[wave.txt](https://github.com/katspaugh/wavesurfer.js/files/448411/wave.txt)

**Comment by kebers** [comment] 2016-09-01 16:33
Hi @chrisparton1991, 
I ran into the exact same problem - when start to zoom into the waveform.
When it's initially rendered to fillParent, evereything is fine - but as soon as zooming in, it's starts to draw huge gaps between pieces of the waveform. With my peakdata (displaying 4 hours)  these gaps are wider than the browser's viewport-width, see screenshots.

Additionally I'm using splitChannels. I've attached screenshots and pre-rendered peaks in the zip-file.

[wavesurfer-issue-814.zip](https://github.com/katspaugh/wavesurfer.js/files/450211/wavesurfer-issue-814.zip)

wavesurfer.init({
	        container: document.querySelector('#waveform'),
	        backend: 'MediaElement',
	        mediaType:'video',
		splitChannels: true,
		renderer: 'MultiCanvas',
		height: 70,
		autoCenter: true
	    });

**Comment by kebers** [comment] 2016-09-02 09:17
Little add-on:
Functionality is broken in v1.1.12 but works with version 1.1.4.
I cannot tell anything about behavior of inbetween versions, i have tested it with the two versions above only. Cheers kai

**Comment by chrisparton1991** [comment] 2016-09-02 22:38
Thanks for the info @kebers!

**Comment by chrisparton1991** [comment] 2016-09-02 22:49
I've added PR #815.

**Comment by kebers** [comment] 2016-09-06 12:56
@chrisparton1991 
I've tested it again with your single-line-change  made with PR #815 - looks a lot better - thanks.
Unfortunately I can see a gap - still, at the end of each canvas, when zooming in - to a certain level.

With the peakdata from my post above it can be seen clearly at zoom level 30 (I've used firefox).
wavesurfer.zoom(30);

at a certain position channel 3/4 of that peakdata make use of the maximum amplitude  - which helped to see those gaps more easy.

Can yo confirm or do i have a local issue ?
kind regards kai

![gap-at-end-of-a-canvas](https://cloud.githubusercontent.com/assets/15983720/18274213/a3719c1a-7441-11e6-8fe8-a5f20db59bfa.jpg)
![gap-at-end-of-a-canvas-firefox-inspector](https://cloud.githubusercontent.com/assets/15983720/18274278/ed68f7b4-7441-11e6-8746-ffce523b0f64.jpg)

**Comment by chrisparton1991** [comment] 2016-09-19 03:21
I'm looking into this, but it's proving quite tricky. I've fixed the gaps, but the canvases don't always quite match up at high zoom levels.

Additionally, the canvases don't render properly if there are only a couple of peaks per canvas, but that's unlikely to occur in a normal use case.

I'll keep on tinkering.

**Comment by mspae** [comment] 2017-09-18 21:55
Duplicate of https://github.com/katspaugh/wavesurfer.js/issues/1181

**Closed by mspae** 2017-09-18 21:55 UTC
Labels: bug
