### ISSUE TITLE
TypeError: this.analyser is null

### ISSUE THREAD

**Issue by webciter** [katspaugh/wavesurfer.js#1853] opened 2020-01-24 15:13 UTC
TypeError: this.analyser is null

Unable to get the example https://wavesurfer-js.org/example/equalizer/ working.

**Comment by thijstriemstra** [comment] 2020-01-28 16:04
i cannot reproduce this on macOs 10.15 with firefox. what browser/os are you using?

**Comment by thijstriemstra** [comment] 2020-02-28 12:43
no feedback, closing.

**Closed by thijstriemstra** 2020-02-28 12:43 UTC
Labels: needs-update
