### ISSUE TITLE
Increasing no play issues with various servers

### ISSUE THREAD

**Issue by nickreale** [katspaugh/wavesurfer.js#758] opened 2016-06-28 21:19 UTC
Katspaugh.. What you have developed here is wonderful. Thank you for your time and commitment to the open source community.

But I am using it in a business environment and we are starting to have playback issues with different servers.

The latest is the audio file comes from a https address and it loads, but does not play.

I would like to pay you for your efforts and help me get this functioning in a way that I can rely upon.

Please let me know if this is a possibility. If not I will repost my issues here and hope we can find a solution. time is critical for me and in order to serve my clients I need this to be resolved ASAP.

thank you for your consideration

**Comment by chanchaldas8890** [comment] 2016-06-29 04:13
Thanks all of you but actually I have a one wav audio file which has three channels.now i need to play all three channels simultaneously but the problem is that when I use setchannel() method its play only one channel at a time.

i have three channel of myaudio.wav
1.pro
2.cus
3.agt

now i want to play channel 1 and 2 both at the same time.but unfortunately its play only on channel at a time.

for this i create three instance of wavesurffer  and set channel for  all instance.
for example:-

var pro_player      = Object.create(WaveSurfer);
var cus_player     = Object.create(WaveSurfer);
var agt_player      = Object.create(WaveSurfer);
_____________________________________________
 pro_player.on('ready', function()
 {       
     pro_player.setChannel(0);
    var timeline = Object.create(pro_player.Timeline);
 
  });

 cus_player.on('ready', function() 
{
        cus_player.setChannel(1);
        var timeline = Object.create(cus_player.Timeline);
 });

 agt_player.on('ready', function() 
{
        agt_player.setChannel(2);
        var timeline = Object.create(agt_player.Timeline);
   });
______________________________________________
its work but now i have a problem, i have three cursor  but i only want one for all three player.
if someone have any slution play forword me Thanks .

**Comment by katspaugh** [comment] 2016-06-29 06:24
@nickreale you can drop me an email with the details.

**Comment by katspaugh** [comment] 2016-07-01 18:11
I guess I can close this. For future inquiries about server-related problems: http://stackoverflow.com/questions/9563887/setting-html5-audio-position/9565178#9565178

**Closed by katspaugh** 2016-07-01 18:11 UTC
Labels: question
