### ISSUE TITLE
How to build with plugins included in output file

### ISSUE THREAD

**Issue by brown353** [katspaugh/wavesurfer.js#363] opened 2015-02-23 19:43 UTC
Can someone add build instructions to the README? Also how can I build so that all the plugins are included in the output wavesurfer.min.js file?

**Comment by katspaugh** [comment] 2015-02-25 09:05
Duplicate of #315.

There's currently no build process for plugins. The plugins can be included into a webpage as is, however. Or just append their contents to the `wavesurfer.min.js` via `cat` or a text editor.

**Closed by katspaugh** 2015-02-25 09:05 UTC
