### ISSUE TITLE
Delay-problem with Start/Stop multiple sounds at the same time

### ISSUE THREAD

**Issue by utjduo** [katspaugh/wavesurfer.js#774] opened 2016-07-10 12:06 UTC
Hi! I'm trying to create a small multitrack player and have made a player with 4 tracks so far that can plays, stops and scrubs at the same time. The only problem I'm having  is when I scrub in the song the tracks doesn't start at the exact same time/place.

I have placed all waveform-tracks into an array and the stop/play code looks like this:

```
'play': function() {
    for (var t in trackUrls) {
        waveforms[t].playPause();
    }
}
```

and the scrubbing-code looks like this:

```
waveforms[index].on('seek', function(e) {
    if (!firstSeek) { //If first seek value
        firstSeek = true;
        for (var t in waveforms) {
            waveforms[t].pause();
            waveforms[t].seekTo(e);
        }
        firstSeek = false;
    }
});
```

I can't seem to get my player to play correctly after scrubbing and I'm out of ideas so anything will help a lot!

I uploaded a test-page for you to see the problem: http://danell.comuf.com/
You can also download the zip with all my code here: http://danell.comuf.com/MT.zip

Thanks!

**Comment by katspaugh** [comment] 2016-07-10 20:42
To remove latency you need to load each track as a channel into a single Web Audio source. I can only recommend reading up on Web Audio starting here: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Basic_concepts_behind_Web_Audio_API

Closing as wontfix since the issue is out of scope of this project.

**Closed by katspaugh** 2016-07-10 20:42 UTC
