### ISSUE TITLE
Please consider pushing an update to npm

### ISSUE THREAD

**Issue by Luca1991** [katspaugh/wavesurfer.js#1677] opened 2019-06-21 16:04 UTC
Hello collegues,
first of all I'd like to say **thank you very much** for this great library, I'm currently using in one of my projects. 

This isn't really an issue/bug request, instead I'd like to remind you to push a new release/update to npm, since I'm stuck with issue #1572 that is now closed and fixed in mainline (with commit 118a1bcd64c18ff1f43638a0a3929961ee626e8f), because the last npm release is from 18th March (and this bug was fixed on 3rd April).

Thank you very much!

**Comment by thijstriemstra** [comment] 2019-06-21 17:06
I understand you want to see a release but I'd like to get the `fetch` change (#1541) in 3.0.0 as well. If you want to help, please take a look and the release will be out sooner.

marking this as a duplicate of #1651

**Closed by thijstriemstra** 2019-06-21 17:06 UTC
Labels: duplicate, question
