### ISSUE TITLE
Centre Line "wiggles"

### ISSUE THREAD

**Issue by Stoyvo** [katspaugh/wavesurfer.js#805] opened 2016-08-24 12:05 UTC
When centre is true, the centre line doesn't stay perfectly centre.

To replicate (while audio is playing), zoom in to waveform, click ahead to start recenter funcrion, watch centre line. The closer you zoom, the more noticeable this becomes.

Suggestion: draw line on parent so position does not need consistent updating. When recentering is needed, use current solution.

**Comment by katspaugh** [comment] 2016-08-24 14:02
I'm fine with the suggested solution.

Do you understand the root cause of the line jumping though? Is it some kind of graphical glitch on the canvas?

**Comment by Stoyvo** [comment] 2016-08-24 14:11
@katspaugh I'll investigate the root cause this evening. I can mostly notice it while CPU is under a decent load.

**Comment by Stoyvo** [comment] 2016-08-25 00:32
@katspaugh Issue is caused by the inner <wave> element, as width value is dynamically changing.

![image](https://cloud.githubusercontent.com/assets/6148099/17952579/f0cb5b66-6a39-11e6-83d7-7b099c9c16a0.png)

**Comment by inigoiparragirre** [comment] 2017-07-04 10:53
Hi, I'm using wavesurfer with autocenter option set to true. I also perceive that when zooming in the application  the bar goes faster and it goes to the right. Any clues how this can be solved? Must recenterOnPosition method be fixed?

Hope this can be solved, thanks! If I have time I will try to check deeper.

**Comment by thijstriemstra** [comment] 2018-10-01 21:43
@dionwiggins do you have any code that shows how to reproduce the problem?

**Comment by Stoyvo** [comment] 2018-10-03 14:19
FWIW, I "resolved" this issue outside of the library by placing a div, position:absolute; ontop of the canvas. It was a hack vs a fix

**Comment by swampthang** [comment] 2018-11-19 15:42
Even though autoCenter set to false, when zoomed in to the end portion of the waveform and clicking to the left of center in the display and then clicking play, the waveform jumps to center around the cursor position and then scrolls until the end is reached again. 

Here's my setup:

```
WaveSurfer.create({
    container: block.wsBox[0], // container is a jQuery obj
    waveColor: '#4286f4',
    progressColor: '#b20000',
    cursorColor: 'rgba(0,0,0,0)',
    height: 100,
    minPxPerSec: timelineFunctions.getPXS(),
    interact: false,
    fillParent: false,
    scrollParent: true,
    partialRender: true,
    pixelRatio: 2,
    autoCenter: false
  });
```
Is my combination of settings causing `autoCenter: false` to be overridden?

**Comment by entonbiba** [comment] 2021-01-25 00:25
@Stoyvo this issue still happening?

**Comment by thijstriemstra** [comment] 2021-03-04 01:56
> this issue still happening? 

No feedback, closing.

**Closed by thijstriemstra** 2021-03-04 01:56 UTC
Labels: bug

**Comment by agfline** [comment] 2022-09-16 11:14
Hi,
I've been struggling for hours with the same issue... 'till I found out I had a `* { scroll-behavior: smooth; }` in my CSS that was messing with autoScroll on high zoom.
Just saying, in case you want to force `scroll-behavior` property on sensible elements.
Thanks for this awesome lib btw ;)
