### ISSUE TITLE
Plugins not defined when using Wavesurfer with TS

### ISSUE THREAD

**Issue by brandonk3nt** [katspaugh/wavesurfer.js#2039] opened 2020-08-12 07:05 UTC
See issue: https://github.com/katspaugh/wavesurfer.js/issues/1705#issuecomment-518038471_

Still getting same issue on latest version 4.0.1:

When using a plugin with this syntax:
```
      plugins: [
        WaveSurfer.timeline.create({ container: this.waveReference })
      ]
```

Getting this error in the browser: `TypeError: Cannot read property 'create' of undefined`

**Comment by thijstriemstra** [comment] 2020-08-12 13:24
These typings (didn't know they existed) probably need to be updated (plugins moved to their own directory).

Marking as duplicate of #2038

**Closed by thijstriemstra** 2020-08-12 13:24 UTC
Labels: duplicate
