### ISSUE TITLE
Seeking .flac files at the end causes a "no supported source" exception

### ISSUE THREAD

**Issue by srdecny** [katspaugh/wavesurfer.js#3534] opened 2024-01-30 13:23 UTC
## Bug description
When loading a. .flac file into the waveform and then seeking very close to the end produces a `Uncaught (in promise) DOMException: Failed to load because no supported source was found.` exception.

## Environment
 - Browser: Chrome

## Minimal code snippet
```
const ws = WaveSurfer.create({
  container: '#waveform',
  url: 'xxx.flac',
})

ws.on('interaction', () => {
  ws.play()
})


```
and then click near the end of the file. Observe the error in the console

## Expected result
It should not crash

## Obtained result

https://github.com/katspaugh/wavesurfer.js/assets/7964806/7529bee6-2819-434e-82e9-f97a1c85dfae

**Comment by srdecny** [comment] 2024-01-30 13:33
<img width="731" alt="image" src="https://github.com/katspaugh/wavesurfer.js/assets/7964806/05291cb1-d675-4ad3-a0b5-a29fee11d5ea">
Another consequence of this bug is that spectrogram is slightly shifted.

**Comment by katspaugh** [comment] 2024-01-30 17:43
I doubt we can do anything about the root cause but the crashing will be silenced in https://github.com/katspaugh/wavesurfer.js/pull/3532

**Comment by katspaugh** [comment] 2024-03-31 11:34
Closing as a duplicate of #3556 (it has more info there).

**Closed by katspaugh** 2024-03-31 11:34 UTC
Labels: bug
