### ISSUE TITLE
Regions playloop has a problem~

### ISSUE THREAD

**Issue by ThoughtZer** [katspaugh/wavesurfer.js#1708] opened 2019-07-31 12:14 UTC
https://github.com/katspaugh/wavesurfer.js/blob/832e114b7be6436458fc351a57699ba169d08676/src/plugin/regions.js#L233-L238

```Math.round(time * 100) / 100``` maybe stop the playloop. But removing the ```Math.round``` is ok. What is the reason for this（```Math.round(time * 100) / 100```）?

**Comment by thijstriemstra** [comment] 2019-08-01 20:55
duplicate of #1655.

can you add your comment to that ticket @ThoughtZer so we keep the discussion in one place?

**Closed by thijstriemstra** 2019-08-01 20:55 UTC
Labels: duplicate, plugins
