### ISSUE TITLE
seekTo() some times gives error

### ISSUE THREAD

**Issue by vishnu-the-developer** [katspaugh/wavesurfer.js#1266] opened 2017-12-07 10:54 UTC
When i put a float value from code to seekTo() the below error shows
**Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-finite.**

**Comment by jonas2515** [comment] 2017-12-07 17:22
Duplicate of #1228

**Closed** 2017-12-21 18:02 UTC
Labels: duplicate
