### ISSUE TITLE
Waveform generation in v7@beta is not sharp and aligned to center

### ISSUE THREAD

**Issue by NegiBaba** [katspaugh/wavesurfer.js#2807] opened 2023-05-30 09:05 UTC
Hey, I was testing the new beta version of wavesurfer and saw that the waveform being generated were not sharp and the position of the bars w.r.t center is also not correct (most of the time it looks like they are shifted a bit in +ve x-axis).

While the same was not an issue in previous version e.g. v6.6.3, where the waveform was as sharp as ever and were aligned with center.

### Wavesurfer.js version(s):
7.0.0-beta.5

### Browser and operating system version(s):
Browser - Chrome v113.0.5672.126
OS - MacOS Ventura

### Code needed to reproduce the issue:

Link to reproduce the issue in [sandbox](https://codesandbox.io/s/vibrant-cdn-wj1888)

### Use behaviour needed to reproduce the issue:
Just check out the codesandbox the audio loads and you will see the cranky waveform and a bit blurry

**Comment by katspaugh** [comment] 2023-05-30 09:31
I can see what you mean. I'll try rendering it with lines instead of rectangles, I think that will look smoother.

Regarding the center alignment, are you trying with a mono file? If audio is mono, it will create an asymmetrical waveform where the top part is positive peaks and the bottom is negative peaks.

**Comment by NegiBaba** [comment] 2023-05-30 09:45
In the sandbox I just looked on the internet to find any random sound to generate waveform for, but in my current project I am recording my audio from a different library and then loading the recorded blob directly to wavesurfer.js. I am pretty sure it's a mono file. 
By any chance do we have any control over rendering symmetrical waveform for mono audio?

**Comment by katspaugh** [comment] 2023-05-30 10:37
I thought asymmetry looked pretty cool and showed more info, but we can make it symmetrical if it's confusing. It would simplify the code actually.

**Comment by NegiBaba** [comment] 2023-05-30 11:09
Great! Let me know if there is something on which I can be of use.

**Comment by TwanLuttik** [comment] 2023-05-30 17:06
@NegiBaba is this what you mean by not sharp?

![CleanShot 2023-05-30 at 10 05 51](https://github.com/katspaugh/wavesurfer.js/assets/19343894/78c9eedc-40cd-4465-9d3f-43054017d0da)

**Comment by piyush-toddleapp** [comment] 2023-05-30 17:27
Hey @TwanLuttik please check the associated link to reproduce the issue. You shall see what I mean by not sharp on that sandbox rather than sharing a picture here.

**Comment by NegiBaba** [comment] 2023-05-30 17:29
Hey @TwanLuttik Kindly check the associated sandbox link that I have attached above. There you shall see the issue that I am concerned about.

**Comment by TwanLuttik** [comment] 2023-05-30 17:32
@NegiBaba I had to temporarily get access to the audio link, but yes, it seems to be the same issue.

**Comment by katspaugh** [comment] 2023-06-05 05:59
@NegiBaba @TwanLuttik does it look sharper for you in beta.6?

**Comment by NegiBaba** [comment] 2023-06-05 08:28
@katspaugh Below are the screenshots I took from both beta.5 and beta.6 . As far as I can tell these do not look any different. 

**Beta.5**
<img width="433" alt="beta 5" src="https://github.com/katspaugh/wavesurfer.js/assets/48850319/69758102-78b5-4dca-b96d-04d155aaf3c0">

**Beta.6**
<img width="435" alt="beta 6" src="https://github.com/katspaugh/wavesurfer.js/assets/48850319/1a8da894-8402-4f2d-b485-e1af316a55a8">

**Comment by NegiBaba** [comment] 2023-06-05 11:58
@katspaugh I was just doing some experiments with canvas and js and I have this piece of code that takes in a canvas/canvasCtx and an array of floats(heights of bars to be drawn) and draws the rounded bars with the help of lineTo and quadraticCurveTo methods. I was thinking of using that code with custom renderer but thought maybe? we can just use that code in here. I had it with lineTo and quadraticCurveTo because roundRect was not supported back when I wrote it.

**Comment by katspaugh** [comment] 2023-06-05 13:34
Sure, if that’s smoother let’s totally go for the quadratic curve. Feel free to open a PR, I’ll be away from PC til next week but can review it.

**Comment by TwanLuttik** [comment] 2023-06-06 01:53
> @NegiBaba @TwanLuttik does it look sharper for you in beta.6?

Beta.5
![CleanShot 2023-06-05 at 16 18 16](https://github.com/katspaugh/wavesurfer.js/assets/19343894/5f57392a-2d6e-48e6-ba67-80118a395bcb)

Beta.6
<img width="816" alt="CleanShot 2023-06-05 at 18 51 03@2x" src="https://github.com/katspaugh/wavesurfer.js/assets/19343894/5841f75d-1c67-4083-be4b-68ab1366a79e">

This is zoomed in btw

**Comment by TwanLuttik** [comment] 2023-06-14 18:39
The issue still occurs for me in version `7.0.0-beta.8`

**Comment by TwanLuttik** [comment] 2023-06-17 21:52
@NegiBaba I look forward to your PR; it would be nice to have this fixed or a temporary workaround or edge cases you have approached.

**Comment by katspaugh** [comment] 2023-06-18 07:31
I think I've fixed by just making the height also 2x for high-DPI screens.

**Closed** 2023-06-18 07:42 UTC
