### ISSUE TITLE
abortController is not defined.

### ISSUE THREAD

**Issue by 44886** [katspaugh/wavesurfer.js#1898] opened 2020-04-02 05:33 UTC
So many people use QuarkBrowser.  https://www.myquark.cn/
but , it do not support abortController.

I use this code :
```
    if (typeof (AbortController) == "undefined") {
        load.getScript("//polyfill.io/v3/polyfill.js?features=AbortController", null);
    }
```

but,Is there other  easy way to show waveform on that browser?

**Comment by thijstriemstra** [comment] 2020-04-02 11:56
duplicate of #1832

**Closed by thijstriemstra** 2020-04-02 11:56 UTC
Labels: duplicate
