### ISSUE TITLE
Unstable after attempting to load consecitve long mp3s.

### ISSUE THREAD

**Issue by tomByrer** [katspaugh/wavesurfer.js#374] opened 2015-03-01 06:15 UTC
When loading a large mp3s (40 minute lecture, 1 hour DJ mix), http://www.wavesurfer.fm/?fill works fine the first time.  Load another afterwards, wavesurfer crashes or won't load.  Chrome & Fx Win7.  Reloading the webpage resets it, so it will work for the first long MP3.

Memory/array issue?

**Comment by katspaugh** [comment] 2015-03-01 07:37
I guess it's a duplicate of #320. Web Audio issue, no known workaround.

**Comment by tomByrer** [comment] 2015-03-01 13:26
> Web Audio issue

I don't think so; I can open same files consecutively in same browsers using native players with perfect playback.
Reopen please, or should I see first if other players have same issue first?  (Though other issue may help, I'm very unsure.)

**Comment by katspaugh** [comment] 2015-03-01 14:26
You might assume I'm indignant in closing useful issues, but unless you do some memory profiling and prove that the memory is hold up in JavaScript I'm not inclined to change my view. I'm reopening and hope you'll find something interesting out. Please, make sure you tell Web Audio from "HTML5" audio.

**Comment by tomByrer** [comment] 2015-03-03 08:33
Sorry, I didn't mean to offend.

[paullewis/music-dna](https://github.com/paullewis/music-dna) will play all my test files in Chrome.  The hour-long ones will hang in Fx, but will play the 40 minute MP3s.

**Comment by katspaugh** [comment] 2015-03-03 09:03
No offence taken :smile: 

Thanks for the link! It seems they use Web Audio's `decodeAudioData` (the same as wavesurfer.js). I'll investigate what can we learn from them.

**Comment by tomByrer** [comment] 2015-03-03 14:47
I should note in the other program, Chrome didn't display any waveform, & fFx barely did.
A few thoughts:
* check how HTML5 game writers handle large arrays & files; they tend to push limits
* perhaps better just to stop & warn when taking too long?
* would one of those fancy new webworkers help?

**Comment by entonbiba** [comment] 2017-02-28 23:03
@tomByrer may you try with the latest version? Many improvements have been made.

**Comment by mspae** [comment] 2017-03-01 10:21
@entonbiba I'm not sure if the changes that were merged recently have fixed this. I think the issue is probably caused by some memory not being collected when loading new audio files, not by the debounce/zoom type of performance issues. I think there is probably no way to fix this without doing timeline analysis to try and find the issue(s)

**Comment by entonbiba** [comment] 2017-03-01 16:03
@mspae yes but we did add the `audiocontext.close()` on the destroy method in the latest version which should fix the memory issues for chrome and firefox as these are the only browsers currently supported.

![image](https://cloud.githubusercontent.com/assets/5193884/23468380/ab2f99f4-fe6e-11e6-9d75-d3d8e3be7b0b.png)

**Comment by mspae** [comment] 2017-03-03 07:02
@entonbiba True. I didn't think of that :p

**Comment by afincato** [comment] 2017-11-22 19:17
comment [283190049](https://github.com/katspaugh/wavesurfer.js/issues/374#issuecomment-283190049) by `entonbiba` solved the problem for me for Firefox and Chrome on iOS 11.1.2, but Safari iOS keeps crashing after the audio track plays for 5-10 seconds.

The mp3 I am loading is ~14mb and works well if it is played with the native `audio` tag.

Do you have any suggestion on maybe segmenting the audio file and recombine it? Would be work better?

**Comment by entonbiba** [comment] 2017-11-25 02:29
@afincato are you using the latest version of safari? May you post the code to test?

**Comment by afincato** [comment] 2017-11-25 16:30
Yes, running the latest version of iOS (`11.1.2`) with latest Safari. I'm wondering if the fact that  I am using an iPhone 6 first-gen causes Safari to lacking in hardware resources and memory. Weirdly enough though, testing the below code with Google Chrome iOS and the new Firefox Quantum for iOS works decently.

Adding the following options in the wavesurfer constructor made it work in Firefox and Chrome for iOS

```
normalize: true,
backend: 'MediaElement',
renderer: 'MultiCanvas',
pixelRatio: 1
```

Here the full code:

```
//++ audio player w/ wavesurfer.js

  var ap_s = document.querySelectorAll('.ap source');
  var ws_pp = document.querySelectorAll('.ws--pp');

  if (document.querySelector('audio') !== null) {
    // init

    var wavesurfers = [].map.call(document.querySelectorAll('.waveform'), function (element) {
      var wavesurfer = Object.create(WaveSurfer);
      wavesurfer.init({
        container: element,
        waveColor: 'white',
        progressColor: '#222',
        hideScrollbar: true,
        scrollParent: true,
        normalize: true,
        backend: 'MediaElement',
        renderer: 'MultiCanvas',
        pixelRatio: 1
      });
      return wavesurfer;
    });

    function formatTime(time) {
      return [
        Math.floor((time % 3600) / 60), // minutes
        ('00' + Math.floor(time % 60)).slice(-2) // seconds
      ].join(':')
    };

    wavesurfers.forEach(function(item) {
      // load up file
      item.load(item.container.parentElement.previousElementSibling.firstElementChild.getAttribute('src'));

      // setup timescore
      item.on('audioprocess', function() {
        item.container.querySelector('.ws--tl-c').innerHTML = formatTime(item.getCurrentTime());
      });
      item.on('ready', function() {
        item.container.querySelector('.ws--tl-t').innerHTML = formatTime(item.getDuration());
      });
    });

    function ws_player (event) {
      if (event.currentTarget.classList.contains('play')) {
        event.currentTarget.classList.remove('play', 'bgc-gr--pulse-dkr');
        event.currentTarget.classList.add('pause');
      } else {
        event.currentTarget.classList.remove('pause');
        event.currentTarget.classList.add('play', 'bgc-gr--pulse-dkr');
      }
    }

    ws_pp.forEach(function(button, i) {
      button.addEventListener('click', ws_player, false);
      var button_i = i;

      button.addEventListener('click', function () {
        wavesurfers.forEach(function (item, i) {
          if(i === button_i) {
            console.log('this is playing! ' + item.container.parentElement.previousElementSibling.firstElementChild.getAttribute('src'));
            item.playPause();
          }
        });
      }, false);
    });

  };
```

**Comment by entonbiba** [comment] 2021-01-24 23:24
@afincato may you try using the latest version? If anything have a look at the sample code from this ticket. https://github.com/katspaugh/wavesurfer.js/issues/2058#issuecomment-761284236

Reopen this one if it's still an issue.

**Closed by entonbiba** 2021-01-24 23:24 UTC
Labels: bug, enhancement
