### ISSUE TITLE
Wave disappears after loading subsequent files with the MediaElement backend

### ISSUE THREAD

**Issue by micahlisonbee** [katspaugh/wavesurfer.js#443] opened 2015-04-23 15:38 UTC
In Chrome (not an issue in Safari/FF).

The waveform disappears after loading a subsequent audio file. The issue is demonstrated clearly on this playlist example page when clicking another play button:

![screen shot 2015-04-23 at 9 37 50 am](https://cloud.githubusercontent.com/assets/1928295/7300915/715f4e92-e99c-11e4-80a6-2d8ce84093ae.png)

http://www.wavesurfer.fm/example/playlist/

It's also apparent on the main page when dragging and dropping a new audio element:

http://www.wavesurfer.fm/

**Comment by katspaugh** [comment] 2015-04-23 15:57
I can't reproduce. The previous waveform does disappear, because it loads the new one. GitHub (which hosts the website) is very slow to serve media files for some reason. But in a couple of seconds a new file appears, that's what I see.

**Comment by micahlisonbee** [comment] 2015-04-23 16:02
Still seeing the issue, I'm on Version Chrome 42.0.2311.90 (64-bit) on OS X 10.10.13

**Comment by katspaugh** [comment] 2015-04-23 17:15
Do you see any errors in the console?

What exactly is the sequence of steps you perform to observe the bug?

**Comment by micahlisonbee** [comment] 2015-04-23 17:44
I navigate to the page, the first wave renders correctly and the waveform shows.

Then I click play on another song in the list, the wave disappears. It never returns, even when going back to the initial wave.

See video: 
http://dropshots.com/micahlisonbee/date/2015-04-23/13:39:23

**Comment by jthrilly** [comment] 2015-07-01 00:25
I see this issue too. Chrome on OSX.

**Comment by berio** [comment] 2015-09-07 14:24
Same error here, it only happens to me when init wavesurfer with AudioElement backend.

**Comment by geeklisted** [comment] 2015-09-07 14:36
I was having the same issue; glad to see I'm not the only one.  This was particularly noticeable for me in Firefox (Linux) and both Chrome and Firefox (Windows).  Chrome seems to handle it more wisely.

By any chance are you initializing Wavesurfer when its DOM element is hidden, has a w/h of 0, or any other kind of display property that might prevent the element from not being accessible?

The above scenario was true in my case, and I 'fixed' the issue by attempting to instantiate Wavesurfer once its particular page area was visible.  Then I stored a flag to denote it had been loaded rather than trying to re-init each time.  This resolved the issue in Chrome / Windows (44.0) for me anyways.

**Comment by geeklisted** [comment] 2015-09-07 14:45
Accidentally commented on a different issue. 

On this topic, are you calling .empty() on your wavesurfer object in-between file loads?

**Comment by jmslovatt** [comment] 2015-09-24 12:56
Sorry, missed your reply. Yep am calling empty between file loads. As a temporary workaround I've found calling redrawBuffer on a timeout means that it now works across the board. Not ideal, but does the job!

**Comment by mattahorton** [comment] 2016-03-13 21:52
Seeing this on Chrome 48.0.2564.116 (64-bit) on Mac OS X El Capitan (10.11.3). Safari functions fine.

**Comment by entonbiba** [comment] 2017-05-16 23:36
closing, working fine on chrome 59+

**Closed by entonbiba** 2017-05-16 23:36 UTC
Labels: bug

**Comment by gadicker** [comment] 2020-03-10 18:46
I know this is closed but just in case someone else has this issue like I did I found it was because I had created WaveSurfer with the partialRender option true.  I set it to false or just don't include it when you create the WaveSurfer object because it defaults to false.
