### ISSUE TITLE
region.setOptions({..}) does not modify the region's color

### ISSUE THREAD

**Issue by omerman** [katspaugh/wavesurfer.js#3879] opened 2024-09-23 22:07 UTC
## Bug description

region.setOptions({..}) does not modify the region's color.

## Environment
 - Browser: Chrome

## Minimal code snippet
Will provide minimal code snippet in the upcoming days, but incase you have a minimal repo of your own to work with, I thought I'd give you a head start

## Expected result
region.setOptions({..}) should be able to update the region's color.

**Comment by lucastheis** [comment] 2024-09-25 18:06
Regarding `clearRegions()`, see issue #3798.

**Comment by katspaugh** [comment] 2024-09-26 06:53
Closing as a duplicate of #3798.

**Comment by omerman** [comment] 2024-09-26 07:05
@katspaugh  But the setOptions part is not duplicate, will this also be addressed? 😢

**Comment by katspaugh** [comment] 2024-09-26 08:53
@omerman thanks for the sponsorship! I’ll prioritize this and the other regions issue. 👍

**Comment by omerman** [comment] 2024-09-26 08:58
@katspaugh Thank you so much for your work 🙏

**Comment by omerman** [comment] 2024-10-01 14:28
@JanMisker Im passing only the start arg, so I guess by default it is also used as a marker
here is my code snippet:

```
regionsPlugin.addRegion({
          id: `tempo_${i}`,
          start: tempoItem,
          color: i === playerIndex ? colors.pink['500'] : colors.gray['400'], // init
          drag: false,
          resize: false,
        });
```

And because a color cannot be updated I have to remove the region and recreate it 😅

**Comment by JanMisker** [comment] 2024-10-01 14:41
@omerman yeah that will be it; because you give no value for `end`, it is a marker and doesn't get a color.

**Comment by omerman** [comment] 2024-10-09 05:11
> @omerman yeah that will be it; because you give no value for `end`, it is a marker and doesn't get a color.

Just to make sure we are both on the same page, 
My regions have colors, the colors just won't be updated and I need to destroy them and re-create them in order to make a color update
<img width="1270" alt="image" src="https://github.com/user-attachments/assets/c67e9601-7d42-4310-94ec-ce521f708b40">

**Comment by katspaugh** [comment] 2024-12-15 09:03
I tried to reproduce this but couldn't so far. Using this example:
https://wavesurfer.xyz/examples/?c1e811ebce69604ce5519feca1d7791e

As you can see it has both regions with an `end` and "markers" w/o an end. Both change their color on click.

**Comment by omerman** [comment] 2024-12-15 21:13
I'll check and let you know, maybe it got fixed along the way and i missed it?

**Comment by katspaugh** [comment] 2024-12-25 11:14
I'll go ahead and close this but please feel free to reopen it if there's some edge condition where color options aren't applied.

**Closed by katspaugh** 2024-12-25 11:14 UTC
Labels: bug, plugins, regions
