### ISSUE TITLE
self is not defined

### ISSUE THREAD

**Issue by sohaibmaavan007** [katspaugh/wavesurfer.js#2359] opened 2021-09-15 15:44 UTC
I am using this plugin in my SSR react application but when start server it gives me error "Reference Error: self is not defined"
at Object.<anonymous> (D:\Maavan\Remixology\MVP\MVP_v1\node_modules\wavesurfer.js\dist\webpack:\WaveSurfer\webpack\universalModuleDefinition:10:2).

![image](https://user-images.githubusercontent.com/71809525/133465555-00d6d38f-84c4-4636-8aa6-bf6a571e7f24.png)

**Comment by thijstriemstra** [comment] 2021-09-21 22:34
duplicate of #2350?

**Closed by thijstriemstra** 2021-09-21 22:34 UTC
Labels: duplicate
