### ISSUE TITLE
exportPCM gives array of null elements.

### ISSUE THREAD

**Issue by tzsk** [katspaugh/wavesurfer.js#1196] opened 2017-08-22 10:49 UTC
### Code needed to reproduce the issue:

```
var h = WaveSurfer.create({
    container: "#" + d,
    normalize: !0
});
h.load('music/file.mp3');
h.on('ready', function() {
    var d = h.exportPCM(512);
    console.log(d);
});

````
### Output:

```
[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,0,0]
```

**Comment by thijstriemstra** [comment] 2017-08-27 13:12
Putting that load call after the ready handler doesn't help either?

**Comment by SalvatoreDuran** [comment] 2017-08-29 20:29
@thijstriemstra nop... And using v2 not working either

**Comment by entonbiba** [comment] 2017-08-31 00:31
@tzsk can you post the code on codepen and post the mp3 here?

**Comment by mspae** [comment] 2017-09-03 12:50
Couldn't reproduce with v2: https://www.webpackbin.com/bins/-Kt6lLLCVsOCxGgZwydZ

Please provide a working reproduction so we can help @SalvatoreDuran @tzsk

**Comment by SalvatoreDuran** [comment] 2017-09-03 14:19
@mspae I have installed any webpack boiler template + your exact code here: https://github.com/SalvatoreDuran/wavesurfer-bug

Result:
On chrome it gives me an array of null and a white window is open.
In Safari (not related to this issue): IndexSizeError (DOM Exception 1): The index is not in the allowed range.

**Comment by mspae** [comment] 2017-09-03 15:06
got it. thanks! I'll investigate.

**Comment by mspae** [comment] 2017-09-03 16:13
Okay so you were using the published version, not the current HEAD state. ( @katspaugh can you publish a new beta version?) – that's why you were still using the buggy code.

To get the current HEAD installed, do:
```
git clone git@github.com:katspaugh/wavesurfer.js.git && cd wavesurfer.js && npm i && npm run build && npm link && cd ../ && npm link wavesurfer.js
```

The Safari issue sounds like #1099 which should also be fixed with the new code.

Please comment if this doesn't fix the issue and we'll reopen.

**Closed by mspae** 2017-09-03 16:13 UTC
Labels: bug, needs-update

**Comment by rAthur** [comment] 2018-01-17 16:46
In my case, the issue was solved by falling back to version 1.2.6!
