### ISSUE TITLE
MediaElement mode and fallback not supported without WebAudio

### ISSUE THREAD

**Issue by pravdinalex** [katspaugh/wavesurfer.js#1662] opened 2019-06-06 13:33 UTC
### Wavesurfer.js version(s):
2.2.1

### Browser and operating system version(s):
IE 11.0.9600 / Windows 8.1

### Code needed to reproduce the issue:
https://wavesurfer-js.org/

error in wavesurfer.js - line 1 column 7139 - Command is not supported by object.
```
{key:"getAudioContext",value:function(){return window.WaveSurferAudioContext||(window.WaveSurferAudioContext=new(window.AudioContext||window.webkitAudioContext)),window.WaveSurferAudioContext}}
```

![image](https://user-images.githubusercontent.com/2210640/59035968-149f9800-8877-11e9-8fa7-bf3ed1de5d48.png)

In my project, even if I explicitly set backend to 'MediaElement', I got this error too. 

Seems, error is caused because of:

```
MediaElement extends WebAudio
...
    constructor(params) {
        super(params);
```
and 
```
WebAudio extends util.Observer {
...
    constructor(params) {
       ...
       this.ac = params.audioContext || this.getAudioContext();
```

i.e. even if backend is MediaElement we ara trying to create audioContext, which is not acessible in IE. 

PS: Why `MediaElement extends WebAudio` ???

**Comment by thijstriemstra** [comment] 2019-06-07 09:17
looks like a duplicate of #1614 @pravdinalex

**Comment by pravdinalex** [comment] 2019-06-10 13:07
really, this combination of manually set options works in IE11 as expected: can play audio with empty visualization.
```
                    audioContext: {},
                    backend: 'MediaElement',
```
But if `backend: 'MediaElement'` is not manualy set, I get error about `command createGainNode not found at object` in webaudio.js :: createVolumeNode()

**Closed** 2019-06-10 19:27 UTC
Labels: needs-update
