### ISSUE TITLE
Unable To play big .ogg File

### ISSUE THREAD

**Issue by ShanMuhammad** [katspaugh/wavesurfer.js#820] opened 2016-09-09 06:06 UTC
First of all, thanks for this awesome library.

I am Trying to play more than 30 min .ogg file but its return error 

>uncaught exception: out of memory

And

> An unknown error occured while processing decodeAudioData.
>EncodingError: The given encoding is not supported.

Could you please help

**Comment by katspaugh** [comment] 2016-09-12 08:49
Duplicate of #796.

**Closed by katspaugh** 2016-09-12 08:49 UTC
