### ISSUE TITLE
The example code is incomplete and app.js is missing

### ISSUE THREAD

**Issue by daihai20081** [katspaugh/wavesurfer.js#2578] opened 2022-09-09 12:02 UTC
# Hey, thank you for testing and contributing to wavesurfer.js!

## Please make sure you can check all of these points below before opening an issue:

(You don't have to post this section)

- [x] I have checked [the FAQ](https://wavesurfer-js.org/faq/) and it doesn't solve my problem.
- [x] I have checked [the documentation](https://wavesurfer-js.org/docs/) and it doesn't solve my problem
- [x] I have searched for [already open issues](https://github.com/katspaugh/wavesurfer.js/issues) which desribe my problem.
- [x] The issue I'm having is related to and caused by wavesurfer.js, not by other software (which maybe packages and uses wavesurfer incorrectly) – In that case you should open the issue on the respective project pages.

### Code needed to reproduce the issue:

(Please reduce your code as much as possible and only post the minimum code needed to reproduce the issue. [A Code pen](http://codepen.io/) is an excellent way to share such code)

### Use behaviour needed to reproduce the issue:

The example code is incomplete and app.js is missing

**Comment by thijstriemstra** [comment] 2022-09-09 23:24
can you be more specific?

**Comment by daihai20081** [comment] 2022-09-12 10:50
Sorry，The example code is incomplete and app.js is missing .File path: wavesurfer.js/tree/master/example/split-wave-point-plot/  I can't find the app.js file。

**Comment by daihai20081** [comment] 2022-09-12 10:51
> Sorry，The example code is incomplete and app.js is missing .File path: wavesurfer.js/tree/master/example/split-wave-point-plot/ I can't find the app.js file。

**Comment by daihai20081** [comment] 2022-09-12 10:51
> can you be more specific?
Sorry，The example code is incomplete and app.js is missing .File path: wavesurfer.js/tree/master/example/split-wave-point-plot/ I can't find the app.js file。

**Comment by daihai20081** [comment] 2022-09-12 10:53
The example “split-wave-point-plot” cannot run completely。

**Comment by othmar52** [comment] 2022-10-09 06:07
> can you be more specific?

i did not dig into the code but i can confirm that https://wavesurfer-js.org/example/split-wave-point-plot/index.html does not work for me:  

![image](https://user-images.githubusercontent.com/7056051/194740814-588fbfa0-c1df-4015-a50d-1f022b83f27f.png)

**Comment by thijstriemstra** [comment] 2023-01-25 10:06
Duplicate of #1286

**Closed by thijstriemstra** 2023-01-25 10:06 UTC
Labels: needs-update
