### ISSUE TITLE
About wavesurfer!

### ISSUE THREAD

**Issue by bleedkaga** [katspaugh/wavesurfer.js#743] opened 2016-06-07 06:48 UTC
Afternoon: 
 I'm use wavesurfer plugin, Init slow, Each initialization time in five seconds! Excuse me, is it possible to increase the initial velocity
Thanks!

**Comment by katspaugh** [comment] 2016-06-07 08:16
Yes, it can be slow for big files, as it decodes them in the browser.
A duplicate of #740.

**Closed by katspaugh** 2016-06-07 08:16 UTC
