### ISSUE TITLE
Wavesurfer Stops Updating on Safari After Resize or Seek

### ISSUE THREAD

**Issue by DrLongGhost** [katspaugh/wavesurfer.js#1416] opened 2018-07-24 15:00 UTC
In Safari on Mac, if you resize the window several times while Wavesurfer is playing, the next time you initiate a playback, the wavesurfer waveform will no longer update to show the audio is playing, although the audio will still be audible.

### Wavesurfer.js version(s):

2.0.5. Likely earlier versions as well.

### Browser version(s):

Seen on Safari on Mac version 11.1.1 and 11.1.2. Likely older versions as well.

### Use behaviour needed to reproduce the issue:

1) Load https://wavesurfer-js.org in Safari
2) Click Play
3) While audio is playing, use mouse to make browser window narrower. Make it wider then narrow several times while audio is playing. Additionally, try clicking on the waveform to move playback to an earlier part of the audio file while audio is playing.
4) It takes anywhere between 30 seconds and 5 minutes to trigger the bug, but eventually wavesurfer reaches a broken state where the audio waveform no longer updates; playback continues to work otherwise despite this. The only way to fix things is to reload the page.

Sometimes the bug won't manifest until you click pause and then click play. Other times clicking on the waveform to jump to an earlier position will break it right away without an additional pause/play click.

Possibly related to https://github.com/katspaugh/wavesurfer.js/issues/1215

**Comment by thijstriemstra** [comment] 2018-11-17 04:57
@DrLongGhost do you still see this issue in Safari 12 (because I don't)?

**Comment by DrLongGhost** [comment] 2018-11-20 14:06
@thijstriemstra - I can confirm that this issue does appear fixed in Safari 12. On iOS 12.1 I was also not able to duplicate.

This is great news since it means the browser sniffing I was using to get around this issue won't be needed once most people have upgraded in another 6 months or so.

I did find a new, minor iOS issue, however. I'll leave it up to you whether or not to ticket it.

In Mobile Safari on iOS 12.1 if you go to https://wavesurfer-js.org and load the site in Portrait orientation and then tilt your phone to Landscape orientation, clicking anywhere on the righthand side of the waveform does not jump the cursor to the correct position. Oddly, if you initially load the site in Landscape, you are able to switch back and forth between Portrait and Landscape without issue.

**Comment by thijstriemstra** [comment] 2018-11-20 14:29
@DrLongGhost can you reproduce that with a simpler example, e.g. without full wavesurfer-js.org site?

**Comment by thijstriemstra** [comment] 2018-12-01 21:55
> On iOS 12.1 I was also not able to duplicate.

That's good news. Closing. Please open a new ticket for remaining issues (if any).

**Closed by thijstriemstra** 2018-12-01 21:55 UTC
Labels: needs-update, safari-issue
