### ISSUE TITLE
Replace AudioContext with OfflineAudioContext to work around Web Audio memory leak

### ISSUE THREAD

**Issue by karimfikry** [katspaugh/wavesurfer.js#326] opened 2015-01-05 23:27 UTC
I used only one instance of the wavesurfer in my application, and frequently I need to change to audio source to be played, but every time I change this audio source it seems that it don't release the old audio buffer. Tested on Chrome Version 39.0.2171.95 (64-bit).

Any idea?

**Comment by katspaugh** [comment] 2015-01-06 11:38
Again, this is a know issue with Web Audio. Please see http://stackoverflow.com/q/19559720/352796.

Closing as duplicate of #77.

**Comment by karimfikry** [comment] 2015-01-06 11:39
So? I think It should be fixed somehow!

**Comment by katspaugh** [comment] 2015-01-06 11:43
We could work it around replacing AudioContext with OfflineAudioContext, but I think it should be fixed in Web Audio implementation of Chrome and others. You might want nudge these guys in their bug trackers.

I'll reopen this with a different title.

**Closed** 2015-01-20 21:49 UTC

**Comment by huhhw** [comment] 2017-05-17 14:53
I used the test, the memory will sometimes be released, but this probability is very low, most of the test or will not be released,
