### ISSUE TITLE
splitChannels not working in 1.3.0 version

### ISSUE THREAD

**Issue by Sharpek** [katspaugh/wavesurfer.js#956] opened 2017-02-02 13:24 UTC
Hello, 

In version 1.3.0 splitChannels is flat. Take a look: 

http://codepen.io/anon/pen/PWRxNQ

**Comment by dmongrel** [comment] 2017-02-03 06:29
@Sharpek see #942, and #945.  These should be fixed now.

**Comment by thijstriemstra** [comment] 2017-02-04 19:57
thx for the report but it's a duplicate of #942.

**Closed by thijstriemstra** 2017-02-04 19:57 UTC
Labels: duplicate
