### ISSUE TITLE
Can't display waveform for long mp3s in Scroll.

### ISSUE THREAD

**Issue by tomByrer** [katspaugh/wavesurfer.js#375] opened 2015-03-01 06:16 UTC
http://www.wavesurfer.fm/?fill will load & display long (40min +) mp3s at least the first time, but http://www.wavesurfer.fm/?scroll will only let you play it; no display or scrolling.

**Comment by katspaugh** [comment] 2015-03-01 07:38
Duplicate of #47, will be fixed if we implement Canvas-based scrolling.

**Closed by katspaugh** 2015-03-01 07:38 UTC
