### ISSUE TITLE
the total duration wavesurfer is giving me is wrong

### ISSUE THREAD

**Issue by Johnrobmiller** [katspaugh/wavesurfer.js#3707] opened 2024-05-16 19:25 UTC
I have a audio file that is exactly 6.84 seconds long. I use js to and my OS to confirm that it exactly that duration. However, when I load it into Wavesurfer and call `ws.getDuration()`, wavesurfer is wrongly reporting that it is 6.81795 seconds long. This was causing a bug in my app that was difficult to troubleshoot.

The duration that wavesurfer is outputting ought to be exactly the same as the actual duration of the audio file.

Note: wavesurfer gets the duration wrong even if it is manually set in the options, as noted here https://github.com/katspaugh/wavesurfer.js/discussions/3656

**Comment by boristopalov** [comment] 2024-06-25 04:22
Hey @Johnrobmiller, were you able to find a workaround for this? Running into the same issue

**Comment by shellRaining** [comment] 2024-09-02 03:18
I try to reproduce with below code

```ts
  audioEl.value.onloadedmetadata = () => {
    console.log("audioEl", audioEl.value?.duration);
  };
  const audioContext = new AudioContext();
  const audioBuffer = await fetch(audioURL)
    .then((value) => value.blob())
    .then((blob) => blob.arrayBuffer())
    .then((buffer) => audioContext.decodeAudioData(buffer));
  console.log("audioBuffer ", audioBuffer.duration);
```

and result is

```plaintext
audioEl 13.374694
audioBuffer  13.32297052154195
```

found that the result of audioContext is right, and another interesting discovery is, when I change the format from mp3 to wav, the result of audioEl and audioContext will be same.

https://github.com/katspaugh/wavesurfer.js/blob/5f32d826e792e992401cb4e7866154b71f55768d/src/wavesurfer.ts#L526-L533

wavesurfer tends to use the built-in duration of the audio element, which leads to inaccuracies. maybe we can exchange their order?

**Comment by aburai** [comment] 2024-09-02 08:55
maybe this info can help [HTML audio object reporting wrong file duration](https://stackoverflow.com/questions/47960743/html-audio-object-reporting-wrong-file-duration)

**Comment by katspaugh** [comment] 2024-12-25 09:36
I'll close this as won't-fix because we take the duration directly from the [HTMLAudioElement's duration](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/duration) and it's consistent with its internal playback timer (i.e. currentTime) and it's also what's displayed on the screen if you set `mediaControls: true`.

There can indeed be a discrepancy with how other apps and libraries decode audio (and HTMLAudioElement is often less accurate) but at least it's consistent with its playback timing.

**Closed by katspaugh** 2024-12-25 09:36 UTC
Labels: bug
