### ISSUE TITLE
Timeline/waveform breaks when zooming - regions

### ISSUE THREAD

**Issue by jeremylach** [katspaugh/wavesurfer.js#825] opened 2016-09-20 16:00 UTC
Using MultiCanvas renderer
Steps to reproduce:
<img width="1061" alt="1" src="https://cloud.githubusercontent.com/assets/447535/18678188/3291ad26-7f29-11e6-9106-52ab6b8ed180.png">
1. Drag a region larger
<img width="1122" alt="2" src="https://cloud.githubusercontent.com/assets/447535/18678189/3297406a-7f29-11e6-8e88-f00ab2298c8f.png">
2. Zoom in 
<img width="1053" alt="screen shot 2016-09-20 at 11 58 55 am" src="https://cloud.githubusercontent.com/assets/447535/18678318/a870ed72-7f29-11e6-875e-0b93c1e5ef00.png">
3. Zoom out... the region's location within the canvas is not updated properly, causing display issues.
<img width="1059" alt="3" src="https://cloud.githubusercontent.com/assets/447535/18678190/3298bb8e-7f29-11e6-8df8-d4e5df93f333.png">

**Comment by chrisparton1991** [comment] 2016-09-21 00:55
@jeremylach, do you know if this occurs with the regular `Canvas` renderer as well? Just curious.

**Comment by jeremylach** [comment] 2016-09-21 14:14
Yes, it does.  In fact without MultiCanvas, zooming past wavesurfer.zoom(6) clears the waveform and shows this issue.  This is with a 37 minute audio.  MultiCanvas definitely performs better.

With MultiCanvas, and **no** regions, I can zoom to 100 with no issues, zooming out to "0" works too.
With MultiCanvas, and regions, I can zoom to 100 with no issues, but zooming out gives this issue described in the report.

**Comment by katspaugh** [comment] 2016-11-19 18:12
@jeremylach can you verify if the problem is solved in version 1.2.6 (I've just released it on npm).

**Comment by jeremylach** [comment] 2016-11-20 17:12
@katspaugh unfortunately I'm seeing the same behavior.  Doesn't seem to be resolved.  The audio I'm using to test is 1 hour and 47 minutes.

**Comment by jeremylach** [comment] 2016-11-20 17:35
This does seem to help quite a bit.  The only issue I'm still seeing is an inconsistency with the timeline numbering.

Initial (zoom 0)
<img width="1073" alt="zoom0_initial" src="https://cloud.githubusercontent.com/assets/447535/20464826/44a35752-af1d-11e6-9a11-70126fdcb663.png">

Zoom 2 (should it really be zoomed in this much from only a increase in zoom level of 2?  Or is it the timeline is off but the waveform is correct?)
<img width="1076" alt="zoom_2" src="https://cloud.githubusercontent.com/assets/447535/20464827/4dc8cd9e-af1d-11e6-93cd-f617661fc659.png">

Zoom 4
<img width="1094" alt="zoom_4" src="https://cloud.githubusercontent.com/assets/447535/20464828/53ee5496-af1d-11e6-95fd-c3b216fd5625.png">

Zoom back to 2
<img width="1085" alt="zoom_2_second" src="https://cloud.githubusercontent.com/assets/447535/20464831/5c3942e6-af1d-11e6-8090-768d45d55e83.png">

Zoom back to 0
<img width="1077" alt="zoom_0_second" src="https://cloud.githubusercontent.com/assets/447535/20464834/62e0a3c8-af1d-11e6-849b-edd9bcf7623c.png">

Manually trigger wavesurfer.zoom(0) ... here we can see the waveform hasnt redrawn (same as above zoom 0), but the timeline has reset to the proper times.
<img width="1058" alt="zoom_0_manual" src="https://cloud.githubusercontent.com/assets/447535/20464836/72af68fc-af1d-11e6-8388-095c9a33a20b.png">

**Comment by jeremylach** [comment] 2016-11-20 17:58
The above example was done with custom primaryLabelInterval and secondaryLabelInterval... here's the same problem illustrated with default timeline settings

Initial state (minPxPerSec = 0)
<img width="1071" alt="zoom_0_initial" src="https://cloud.githubusercontent.com/assets/447535/20464943/84f0d840-af20-11e6-9f8c-ecd03580a444.png">

Zoom 2
<img width="1067" alt="zoom_2_" src="https://cloud.githubusercontent.com/assets/447535/20464944/87c20b84-af20-11e6-8b8b-f412cfd2edd5.png">

Zoom 0
<img width="1072" alt="zoom_0_second_" src="https://cloud.githubusercontent.com/assets/447535/20464946/8a474a5e-af20-11e6-92d3-734b9dd1b89c.png">

Zoom 0 with wavesurfer.zoom(0)
<img width="1075" alt="zoom_0_force" src="https://cloud.githubusercontent.com/assets/447535/20464947/8c755ac8-af20-11e6-9bd6-9a431ae3d5e5.png">

**Comment by katspaugh** [comment] 2016-11-21 07:36
@jeremylach thanks! I'll take a look at the timeline.

**Comment by katspaugh** [comment] 2016-11-28 10:31
Just a heads up: I haven't had a chance to work on this this weekend, but keeping tabs on this issue.

**Comment by katspaugh** [comment] 2016-12-03 11:30
@jeremylach the timeline issue should be solved in v 1.2.7 (on npm). Can you take a look?

**Comment by jeremylach** [comment] 2016-12-04 01:26
@katspaugh unfortunately I am seeing this issue persisting.  The workaround by calling the .zoom(0) function twice does seem to work though.  I can .zoom() to any number then call .zoom(0) 2 times and the timeline will reset to the original state.

**Comment by katspaugh** [comment] 2016-12-04 10:05
@jeremylach I've just realized I forgot to publish to npm. Were you trying v 1.2.7?
Can you reproduce your issue on http://wavesurfer-js.org/example/zoom/ ? If not, could you share your test-case via codepen?

**Comment by jeremylach** [comment] 2016-12-05 14:11
Yes I downloaded the zip from the github page, 1.2.7.  I'll take a look at the zoom example or create my own for you to see.

**Comment by jeremylach** [comment] 2016-12-05 16:08
@katspaugh I am seeing the same behavior on the wavesurfer zoom example... Drag the slider in to zoom, then drag back out.  The timeline does not zoom out entirely and does not look like the way it started.

**Comment by katspaugh** [comment] 2016-12-05 16:55
Ah, thanks, now I see it too!

**Comment by katspaugh** [comment] 2016-12-05 17:11
It appears, it was a problem with that particular page, though. The left-most position of the slider didn't match the initial zoom of the waveform. Now it should be fine.

Otherwise, is there any other way to reproduce your issue?

**Comment by jeremylach** [comment] 2016-12-05 19:16
I modified your zoom example as a codepen, to match my wavesurfer config, and at first I could not figure out why it seemed to be working on the codepen but not my site.  I then realized that if I removed the regions altogether, or added them to the wavesurfer BEFORE I initialize the timeline then it works like your example.  In my code, I added the regions AFTER I initialized the timeline.  I am not sure if this is significant or something to note in the docs/change in the code but this seems to have fixed the problem.

Here we see how my code was set up, regions added after the timeline, and the bug I've been describing is present.
[http://codepen.io/jeremylach/pen/zoWdyo?editors=1011](http://codepen.io/jeremylach/pen/zoWdyo?editors=1011)

**Comment by katspaugh** [comment] 2016-12-06 13:59
Sounds like a bug, I'll take a look. Thanks for helping to figure this out.

**Comment by katspaugh** [comment] 2016-12-13 17:16
Closing this one. The last comment by @jeremylach to be solved in #895.

**Comment by piem** [comment] 2017-07-01 18:34
hi all. any chance 4ee2b298 could be merged in the `next` branch? atm, the regions are updated only when zooming in, not when zooming out. the timeline plugin also appears to have a similar issue.

**Closed** 2017-10-10 23:32 UTC
Labels: bounty, bug, plugins

**Comment by heitorb** [comment] 2018-08-23 14:28
I just posted on #895 and someone ask for clarification but the thread got locked. Not accepting my comment. To clarify, it is the very first issue reported here that I am seeing. The waveform (and regions) disappears when zooming out. Zooming in is fine. I don't see any logs but i will work on putting some sample of on codepen or somewhere so you can see it.
