### ISSUE TITLE
Incomplete browser-side rendering

### ISSUE THREAD

**Issue by jameyquinn** [katspaugh/wavesurfer.js#1855] opened 2020-01-25 22:23 UTC
Every one of the many audios I have are failing to render waveforms fully - a flatline at the end of varying length. This occurs regardless of the volume of sound at the end of the file. I include a sample below. It appears that audios longer than 60s render fully with no flat line at the end.

### Wavesurfer.js version(s):
v3.3.1 and v2.2 

### Browser and operating system version(s):
all, renders identically on chrome, firefox latest

### Code needed to reproduce the issue:
waveform config...
```
    const wavesurfer = WaveSurfer.create({
      audioRate: 1.0,
      barHeight: 2,
      barMinHeight: 0.25,
      container: "#waveform-" + id,
      cursorColor: "#66f",
      fillParent: false,
      minPxPerSec: 10,
      progressColor: "purple",
      scrollParent: true,
      waveColor: "red"
    })
```
<img width="201" alt="Screenshot 2020-01-25 14 05 35" src="https://user-images.githubusercontent.com/2664018/73128029-81fc6680-3fc9-11ea-9ea7-64117a183184.png">
<img width="522" alt="Screenshot 2020-01-25 23 22 32" src="https://user-images.githubusercontent.com/2664018/73128038-a6584300-3fc9-11ea-8225-a2a44c97dc5c.png">

**Comment by thijstriemstra** [comment] 2020-01-28 16:06
@jameyquinn these config settings do not match the screenshot(s), there are no bars visible. Also, try removing the `minPxPerSec` option.

**Comment by thijstriemstra** [comment] 2020-02-28 17:03
no feedback, closing.

**Closed by thijstriemstra** 2020-02-28 17:03 UTC
Labels: needs-update, question

**Comment by DSRCFeroz** [comment] 2020-09-03 11:09
Facing the same issue. i have noticed that if the fill parent is set to true it works fine. but, based on my requirements i cant do that.
here is the sample wave. Both are created with same audio file the only difference is the fill parent.
![image](https://user-images.githubusercontent.com/59431855/92105421-6fb89580-ee00-11ea-9a43-86ce1a6deb4d.png)
**WaveSurfer Version** - 4.0.1
**Code Sample:**
var wavesurfer = WaveSurfer.create({
  container: '#waveform',
    waveColor: '#e81a48',
    progressColor: '#D3D3D3',
    cursorWidth: 6,
    cursorColor: '#5c6a77',
    fillParent: false,
    minPxPerSec: 30,
})
**NOTE:** just to make sure weather the issue is not in the previous versions. i picked the lower versions. it worked fine on 1.4.0 but not after that.
