### ISSUE TITLE
toggleMute() is not return audio.

### ISSUE THREAD

**Issue by iagosilvamelo** [katspaugh/wavesurfer.js#1703] opened 2019-07-26 16:23 UTC
Good afternoon, how are you?
i'm development a audio player but the toggleMute() is muted audio and is not return audio.

This is my code:

```
$("#playerMute").click( e => {
    e.target.classList.toggle('active');
    wavesurfer.toggleMute();
});
```
Thanks for your attention.

**Comment by thijstriemstra** [comment] 2019-07-26 18:56
@iagosilvamelo what is the wavesurfer.js configuration you are using?

> and is not return audio.

what do you mean?

**Comment by iagosilvamelo** [comment] 2019-07-26 19:21
Helo @thijstriemstra.
This is my wavesurfer instance:
```
const wavesurfer = WaveSurfer.create({
    container: document.querySelector('#waveform'),
    waveColor: '#0E8F84',
    progressColor: '#23514C',
    backend: 'MediaElement',
    hideScrollbar: true,
    normalize: true,
    plugins: [
        WaveSurfer.cursor.create({
            showTime: true,
            opacity: 0.6,
            customShowTimeStyle: {
                'background-color': '#000',
                color: '#fff',
                padding: '2px',
                'font-size': '12px'
            }
        })
     ]
});
```

When activating the function toggleMute() to click button, the audio is muted, this is ok. With audio muted when activating the function toggleMute() to click button, mute is not disabled.

I tried with setMute(true) and false and setMute(1) and 0. It didn't work either.

Sorry my english, hehehe.

**Comment by thijstriemstra** [comment] 2019-07-26 20:57
what version of wavesurfer.js?

**Comment by iagosilvamelo** [comment] 2019-07-29 12:34
3.0.0

**Comment by aburai** [comment] 2019-08-02 20:10
i can reproduce this in v3. when i use `toggleMute` the volume was not restored and stays on 0
i will investigate and create a PR when i found a solution

**Comment by iagosilvamelo** [comment] 2019-08-02 20:21
I ended up doing like this:

```
setVol(e) {
        this.volume = e.target.value;
        this.player.setVolume(e.target.value);
},
mute() {
        this.player.setVolume(0);
        $("#playerVolume").val(0)
},
desmute() {
        this.player.setVolume(this.volume);
        $("#playerVolume").val(this.volume)
},
```
I'm not using mute.

**Comment by aburai** [comment] 2019-08-02 21:11
i think it depends on this change for backend MediaElement
```
        // only needed for MediaElement backend
        if (this.params.backend === 'MediaElement') {
            this.backend.on('seek', () => {
                this.drawer.progress(this.backend.getPlayedPercents());
            });

            this.backend.on('volume', () => {
                let newVolume = this.getVolume();
                this.fireEvent('volume', newVolume);

                if (this.backend.isMuted !== this.isMuted) {
                    this.isMuted = this.backend.isMuted;
                    this.fireEvent('mute', this.isMuted);
                }
            });
        }
```

**Comment by thijstriemstra** [comment] 2019-09-18 19:05
so this is a bug @aburai?

**Comment by aburai** [comment] 2019-09-24 20:12
i think so, but i can test this only in my configuration
i have removed this part and it works for me, maybe someone else can check this
```
                if (this.backend.isMuted !== this.isMuted) {
                    this.isMuted = this.backend.isMuted;
                    this.fireEvent('mute', this.isMuted);
                }
```

**Comment by adjkldd** [comment] 2019-09-30 03:55
emmm. I get the same problem. In a word, one `toggleMute`, two `mute` event happen. And somehow the second 'mute' event set `isMuted` to `false`. Below is the reproducing link.

https://codepen.io/ldd/pen/vYBwPXz

**Comment by thijstriemstra** [comment] 2019-10-02 15:04
we can add you to the repository collaborators @aburai cc @katspaugh

**Comment by aburai** [comment] 2019-10-02 15:56
I would gladly do anything to help.

**Comment by katspaugh** [comment] 2019-10-02 16:39
Cool, added! Wilkommen im Team, André! 🙂

**Comment by aburai** [comment] 2019-10-02 16:42
Danke.

**Comment by adjkldd** [comment] 2019-10-09 01:46
> @adjkldd can you check, if my change fixes your problem?
> if you don't want to clone, edit, build and link the main repo,
> you can temporary install my fork and test.
> set `"wavesurfer.js": "https://github.com/aburai/wavesurfer.js.git"` in your package.json
> If it works for you, we / i can create a pull request.

It indeed fixes my problem after I comment the code.
```
if (this.backend.isMuted !== this.isMuted) {
    this.isMuted = this.backend.isMuted;
    this.fireEvent('mute', this.isMuted);
}
```

**Comment by entonbiba** [comment] 2021-01-26 01:03
fixed with merge https://github.com/katspaugh/wavesurfer.js/pull/1966

**Closed by entonbiba** 2021-01-26 01:03 UTC
Labels: bug
