### ISSUE TITLE
(1.0.4) MediaElement - interaction reports getCurrentTime() of 0

### ISSUE THREAD

**Issue by geeklisted** [katspaugh/wavesurfer.js#536] opened 2015-10-05 13:37 UTC
Using wavesurfer version 1.0.4.  I've encountered some cases where - even though WebAudio is supported - wavesurfer will not play a WAV file.  Specifically, this happens in Firefox 38.2 ESR.

As a result, I am attempting to use 'MediaElement' as the backend and its seems to work pretty well (minus more coarseness on when events are fired).

Unfortunately, getCurrentTime() and setCurrentTime() do not appear to work correctly.

When clicking within the audio clip buffer, the 'seek' event reports a getCurrentTime() of 0.

When attempting to setCurrentTime() on the object, time always gets set to 0.

Strangely, when 'audioprocess' event is fired, the getCurrentTime() value is correct.

Example:

wavesurfer.init({
                    container: document.getElementById(key + '_audio'),
                    backend: 'MediaElement',
                    waveColor: 'green',
                    progressColor: '#31C6CD',
                    cursorWidth: 2,
                    height: 52,
                    hideScrollbar: true,
                    scrollParent: false,
                    fillParent: true
                });

wavesurfer.on('seek', function() {
        $log.info('seeking on key', key, 'at time', wavesurfer.getCurrentTime());
// always reports 0
});

$scope.setTimeCode = function(_key, _playbackTime) {
            if (_playbackTime) {

```
            $scope.updateTimeCodes(_key, _playbackTime);

            if ($scope.wavesurfers[_key]) {
                //seekTo takes a progress %
                var progress = _playbackTime / $scope.wavesurfers[_key].getDuration();
                $scope.wavesurfers[_key].seekTo( progress );
```

 // always goes to 0
                }
            }
        };

**Comment by katspaugh** [comment] 2015-10-05 13:49
I cannot reproduce on http://wavesurfer-js.org/example/audio-element/

```javascript
> wavesurfer.on('seek', function () { console.log(arguments, wavesurfer.getCurrentTime()); });
```
```
< Object {name: "seek"}
< VM463:2 [0.18333333333333332] 3.991878
< VM463:2 [0.28218390804597704] 6.144238
< VM463:2 [0.39022988505747125] 8.496818
< VM463:2 [0.4764367816091954] 10.373876
```

Can you create a codepen?

**Comment by geeklisted** [comment] 2015-10-05 14:34
Thanks for response.  Might be difficult to get something together on codepen very quickly but I will try.

I added a log on 'arguments' and it does appear to be receiving the proper progress value; however, wavesurfer.getCurrentTime() reports 0.

Would upgrading to 1.0.42 make any difference?

Again, this issue does not occur when using WebAudio.

**Comment by geeklisted** [comment] 2015-10-06 23:21
So interesting turn of events.  I moved my wavesurfers (dynamic) back to WebAudio and created a single AudioContext that is used by each Wavesurfer.  My problem with using wavesurfer / WebAudio with Firefox 38.2 ESR is now resolved.  I still think there is an issue getting time with MediaElement but if the team doesn't feel this is a worthwhile issue, please feel free to close.

**Comment by katspaugh** [comment] 2015-10-07 08:28
I'm closing it, since I cannot reproduce it.

**Comment by arian1123** [comment] 2015-11-02 03:07
I had the issue with certain mp3 files. Ive used 100s of files for wavesurfer and never had this issue. It almost seems random but @katspaugh I can provide the file with which I had the issue. Also only an issue in firefox.

**Comment by arian1123** [comment] 2015-11-02 03:11
Also my issue was with getDuration(), not getCurrentTime()

**Comment by katspaugh** [comment] 2015-11-02 09:24
@arian1123 please send me the mp3 file to katspaugh@gmail.com, I'll have a look.

**Comment by arian1123** [comment] 2015-11-02 16:29
Sent.

**Closed** 2016-11-13 12:04 UTC
