### ISSUE TITLE
RangeError: Invalid array length

### ISSUE THREAD

**Issue by albertocubeddu** [katspaugh/wavesurfer.js#3932] opened 2024-11-13 10:00 UTC
## Bug description
Adding the container inside a div with flex throws an error.

## Environment
 - Browser: Chrome

## Minimal code snippet
`"use client"
import { useWavesurfer } from '@wavesurfer/react';
import { RotateCcw, PauseIcon, PlayIcon, RotateCw, LoaderCircle, CircleX } from 'lucide-react';
import { useCallback, useRef, useMemo, useEffect } from 'react';
import { cn } from "@/lib/utils"
import { Skeleton } from '@/components/ui/skeleton';

interface WaveFormProps
{
    url: string;
}

export default function WaveForm ( { url }: WaveFormProps )
{
    const containerRef = useRef<HTMLDivElement | null>( null )

    const { wavesurfer, isReady, isPlaying } = useWavesurfer( {
        url: url,
        container: containerRef,
        waveColor: '#dddddd',
        progressColor: '#6d28d9',
        height: 100,
        barWidth: 3,
        barGap: 2,
        barRadius: 4,
        autoplay: false,
    } );

    wavesurfer?.on( 'error', ( error ) =>
    {
        console.error( 'Wavesurfer error:', error );
    } );

    const onPlayPause = useCallback( () =>
    {
        if ( !isReady )
        {
            return;
        }
        wavesurfer?.playPause();
    }, [ wavesurfer, isReady ] );

    const onClickSkipSeconds = useCallback( ( number: number ) =>
    {
        if ( !isReady )
        {
            return;
        }
        wavesurfer?.skip( number );
    }, [ wavesurfer, isReady ] );

    useEffect( () =>
    {
        console.log( 'remove the flex from the classname and everything works' );
    }, [] );

    return (
        <div className="w-full">

            <div className="flex">

                <div ref={ containerRef } />

            </div>
        </div>
    )
}`

## Expected result
It should always be displayed.

P.S. I discovered this behaviour as my production environment waveform is triggering "Container not found" and while trying to debug one functionality at a time, I discovered this weird case. I will lodge a ticket as soon as I can replicate "Container not found" in a logical way, as for now, it's triggered randomly.

## Obtained result
Error

## Screenshots
![image](https://github.com/user-attachments/assets/aaa95fab-9bdd-496a-98bf-634da2b5aaf7)

If you change it like this: 
![image](https://github.com/user-attachments/assets/b359d5e8-6e53-4335-9610-0287f1f9ad26)
everything works fine.

**Comment by albertocubeddu** [comment] 2024-11-13 10:22
Works fine using : 

![image](https://github.com/user-attachments/assets/251732ee-2e69-4120-9c8f-863335e54509)

**Comment by katspaugh** [comment] 2024-11-14 14:31
Seems to be a duplicate of https://github.com/katspaugh/wavesurfer.js/issues/3923

**Closed by katspaugh** 2024-11-14 14:31 UTC
Labels: bug
