### ISSUE TITLE
MultiCanvas Renderer and Zoom - Current Indicator place is changing

### ISSUE THREAD

**Issue by samih-dev** [katspaugh/wavesurfer.js#781] opened 2016-07-24 06:26 UTC
Hi
Example can be found here:
http://codepen.io/SamihAbuawad/pen/yJjrrN

I'm using MultiCanvas as renderer (Thanks to @chrisparton1991), after setting the indicator to specific point in a wave while the audio is  paused (try the start of the first wave), and then trying to zoom, the indicator place is being changed.

Anyone faced the same issue? is there any workarouds/fix?

Thanks! 
Samih.

**Comment by chrisparton1991** [comment] 2016-07-28 04:35
Sounds similar to #778, hopefully they're caused by the same thing.

**Comment by chrisparton1991** [comment] 2016-07-28 05:11
Can reproduce using v1.1.2 using MultiCanvas renderer, which is a relatively old release. This likely isn't the same cause as #778.

**Comment by chrisparton1991** [comment] 2016-07-28 05:47
It behaves the same until multiple canvases are used by the multicanvas renderer under the hood. Something isn't taking the width of all the canvases into consideration.

This means that if you set `maxCanvasSize: 32000`, you will be able to zoom in further before this behaviour is exhibited. The tradeoff is that some browsers will not render canvases that large.

I'm working on finding a proper solution at any rate.

**Comment by chrisparton1991** [comment] 2016-07-28 06:06
Bars don't seem to be affected. Setting `barWidth: 1` is a workaround for this issue, if you can live with having bars. This makes me think this issue is in the MultiCanvas `drawWave` method.

**Comment by chrisparton1991** [comment] 2016-07-28 07:34
Found the issue, I was incorrectly dividing by the canvas size in a length calculation in the multiCanvas `drawWave` method.

**Comment by chrisparton1991** [comment] 2016-07-28 10:43
I've been trying to figure this one out for the past few hours, it's a tricky one.

The cause is essentially that the multicanvas waveform rendering code divides up the waveform into equal chunks per canvas, but the canvases aren't equal width. If the waveform width is 1000 and maxCanvasSize is 400, you'll have canvases of widths 400, 400 and 200. These three canvases will be apportioned the same amount of peak data to render, which is incorrect.

A solution still eludes me.

**Comment by katspaugh** [comment] 2016-07-28 10:49
Can we perhaps make the last canvas also 400 and have a common container that would cut off the remaining 200 px (via `overflow: hidden`)?

**Comment by chrisparton1991** [comment] 2016-07-28 11:23
I think I have a solution, but I'll have to continue looking at it after work tomorrow. Baaically, instead of having that 400/400/200 split, I divide then equally (333.3/333.3/333.3).

**Comment by samih-dev** [comment] 2016-07-29 06:29
Hi chrisparton1991 thanks for the help

Regarding the using barWidth: 1, I tried but I got the same behavior with an audio which 20+ minutes long.

The audio I'm having is private so I can't upload it to have codepen for it - sorry 

I hope you find the fix soon.

**Comment by chrisparton1991** [comment] 2016-07-31 22:36
@samih-dev did you see my comment on PR #785? I've hopefully got a solution there. I've attached a zip file containing a test setup that you can run locally (just open the html file in the src directory).

I've noticed that there's a small jump whenever an additional canvas is introduced, although the progress indicator stays in the correct space. I suspect this is caused by a reapportioning of the peak data to the canvases. Increasing the `maxCanvasSize` will minimize the impact of this if it matters to you.

**Comment by samih-dev** [comment] 2016-08-01 06:57
Thanks @chrisparton1991!
The issue is fixed I tried also with audio file which is 20min+ length.

one minor issue is that sometimes when having multi canvases used to draw the wave,  the click in a point in the wave isn't accurate - the midLine  jumps ahead a little ~ 100px.
I have checked if this also hapeening on the current version I'm using 1.1.8, its not reporduced, so maybe its happening because of the changes you made?

**Comment by chrisparton1991** [comment] 2016-08-02 01:10
That's great news @samih-dev :) I'll take a look at that clicking issue sometime in the next few days. Combining multicanvas with zoom is tricky, because any small inaccuracies get amplified as the zoom factor increases, especially for a large audio file like yours. I'll keep you posted as I investigate a solution.

**Comment by moyara** [comment] 2016-08-09 00:22
Hi @chrisparton1991 Thanks for your great works around the multi canvas. I also have inaccuracy issue with zoom factor. Even I'm using 7mins audio, there is noticeable gap between the wave and audio. I'm using zoomLevel=20 now.

**Comment by chrisparton1991** [comment] 2016-08-09 00:29
Hi @moyara, thanks for the feedback. I've been flat out this past week, I'll try to fix this issue soon. Sorry to keep you guys waiting!

**Comment by chrisparton1991** [comment] 2016-08-09 12:59
@samih-dev and @moyara, I've opened a new PR (#789) that I hope will fix your issues. Fingers crossed!

**Comment by chrisparton1991** [comment] 2016-08-12 08:22
This has been merged in now. Any chance of a new release with the fix, @katspaugh?

**Closed** 2016-08-12 08:22 UTC

**Comment by katspaugh** [comment] 2016-08-12 09:24
Released as 1.1.11.

**Comment by samih-dev** [comment] 2016-08-13 13:48
thanks @chrisparton1991. @katspaugh for the great help!

I'll test this soon and provide final feedback.
