### ISSUE TITLE
load waveform as the audio loads

### ISSUE THREAD

**Issue by theoutaboy** [katspaugh/wavesurfer.js#869] opened 2016-11-24 00:57 UTC
Hi Katspaugh!

Is there a way to load in the wave form as the audio is being downloaded to the client-side? 

For example: the waveform is just a straight line, and as pieces of the audio are being downloaded, the waveform is creating the peaks, allowing the user to play music as it loads.

Thanks!

**Comment by katspaugh** [comment] 2016-11-24 09:26
Duplicate of #488. Tl;dr: no.

**Closed by katspaugh** 2016-11-24 09:26 UTC
