### ISSUE TITLE
Peaks get cut off on certain widths, when loading my own peaks JSON

### ISSUE THREAD

**Issue by ffxsam** [katspaugh/wavesurfer.js#1230] opened 2017-10-13 17:03 UTC
I'm loading my own pre-rendered peaks into Wavesurfer (an array of about 900 samples). On most browser widths, it looks fine:

![image](https://user-images.githubusercontent.com/12532733/31557070-06253878-b00d-11e7-9a1b-c624edafd85d.png)

But at smaller widths, half the waveform is missing:

![image](https://user-images.githubusercontent.com/12532733/31557113-2d96a46e-b00d-11e7-907e-66dc5307828e.png)

### Wavesurfer.js version(s):
1.3.7

### Browser version(s):
Chrome 61

### Code needed to reproduce the issue:

https://codesandbox.io/s/vvKqQwwm

**Comment by ffxsam** [comment] 2017-10-13 17:12
@katspaugh Any ideas on this? I couldn't get the recommended [audiowaveform](https://github.com/bbc/audiowaveform) app compiled properly for Amazon Linux, so I'm using something else on the server side, using a special WebAudio implementation in Node.js.

**Comment by ffxsam** [comment] 2017-10-13 23:30
BTW, I managed to get audiowaveform compiled on Amazon Linux. The result was not so great:

![image](https://user-images.githubusercontent.com/12532733/31569901-73897f6e-b044-11e7-9e19-e7849ee3382f.png)

😆 

I followed the exact recommended usage, `audiowaveform -i some-file.mp3 --pixels-per-second 10 -b 8 -o some-file.json` and this is what it came up with. I don't think this program spits out the proper peaks:

```
[0,0,0,0,-22,24,-31,22,-26,23,-17,18,-11,11,-23,16,-21,13,-11,12,-41,45, ...
```

Pretty sure it should be a double ranging from -1 to 1.

**Comment by alexlarichev** [comment] 2017-10-14 19:03
@ffxsam Excuse me sir, what did you mean by 

> I took the output of audiowaveform and scaled it properly (divided by 126) and plugged that into Wavesurfer. ?

I've got the same issue and can't fix it.

**Comment by ffxsam** [comment] 2017-10-14 19:05
@alexlarichev Pretty simple. JavaScript code below:

```js
const peaks = audiowaveformResult.data.map(d => d/ 126);
```

**Comment by mspae** [comment] 2017-10-15 08:26
Can confirm. Also happens with `v2beta-02`. Also happens with mp3 and with WebAudio backend. Only happens when the width of the waveform is small (~ smaller than 250px) – I think this is maybe the same as #1207

**Comment by ffxsam** [comment] 2017-10-15 20:08
I'm willing to pay anyone who's able to fix this issue this week. Email me at `c2FtQG1zZ2JveC5tZQ==` if interested (base64-decode that to get my email address).

@mspae @katspaugh

**Comment by mspae** [comment] 2017-10-22 11:38
I'm sorry @ffxsam I currently don't have the time resources to commit on fixing this in a certain time frame. But of course we will try and fix it ASAP. Thank you for the offer!

**Comment by ffxsam** [comment] 2017-10-22 14:01
No problem. I actually wound up writing my own waveform play control from scratch, because I desperately needed something that works. :) All is well!

**Comment by mspae** [comment] 2017-10-23 21:56
Issue seems to be resolved when using 2.0.0-beta02

I can confirm it still happens on 1.4.0 (latest v1): https://codesandbox.io/s/ko4z2qk8y5

Please check @ffxsam  https://codesandbox.io/s/p75r8m6587

I'm changing the label on this issue.

**Comment by ffxsam** [comment] 2017-10-23 21:58
Glad to hear it's resolved in 2.0!

**Comment by dtbaker** [comment] 2017-10-25 01:08
I just ran into this. So glad there's a fix!

![image](https://user-images.githubusercontent.com/543073/31975468-d205a264-b974-11e7-9c6c-b07f6cf067cd.png)

Testing 2.0 now...

**Comment by thijstriemstra** [comment] 2017-12-21 18:58
Fixed in 2.0? cool, closing.

**Closed by thijstriemstra** 2017-12-21 18:58 UTC
Labels: bug, v1

**Comment by 15838028035** [comment] 2019-01-14 04:17
@dtbaker  could you share your demo ?
@ffxsam  could you share your demo ?

**Comment by notonlybutalso** [comment] 2019-03-06 20:51
Hey,

My peak file values range from -1 to +1 but when loading back in with teh same MPS and passing in the peaks using 'MediaElement' i just get a massive block indistinguishable form the original waveform.

Am I missing something?

Thanks in advance!

**Comment by notonlybutalso** [comment] 2019-03-06 20:57
> Hey,
> 
> My peak file values range from -1 to +1 but when loading back in with the same MP3 and passing in the peaks using 'MediaElement' i just get a massive block indistinguishable form the original waveform.
> 
> Am I missing something?
> 
> Thanks in advance!

Just in case anyone else finds themselves in this situation, its the peak file format it has to be [number, number] and not ["number","number"]

Hope that helps,

Mike
