### ISSUE TITLE
Waveform rendered uncorrect when zooming

### ISSUE THREAD

**Issue by Mozfe** [katspaugh/wavesurfer.js#1577] opened 2019-03-01 05:40 UTC
Steps to reproduce this issue:
1. Let the audio plays for a while.
2. Drag the slider to zoom in
![image](https://user-images.githubusercontent.com/19956458/53618307-bdf64280-3c25-11e9-9b89-235734e64846.png)
3. And then click on the left part of the slider to zoom out.
![image](https://user-images.githubusercontent.com/19956458/53618410-1cbbbc00-3c26-11e9-81c9-dfabcdedb6b1.png)

Browser Version:  Chrome 72.0.3626.119
Wavesurfer Version: 2.1.3
It can be found on the Zoom Example Page(https://wavesurfer-js.org/example/zoom/index.html).

Is there anyway to solve it?
Thanks!

**Comment by thijstriemstra** [comment] 2019-03-03 21:19
can you try if PR #1570 fixes it?

**Comment by thijstriemstra** [comment] 2019-03-12 23:49
I tested https://wavesurfer-js.org/example/zoom/index.html (that uses v2.2.0 at time of this writing) and can't reproduce it, so it seems to be fixed with #1570. Closing.

**Closed by thijstriemstra** 2019-03-12 23:49 UTC
Labels: needs-update
