### ISSUE TITLE
Too many memory is consumed with two instances of the wavesurfer in one page

### ISSUE THREAD

**Issue by karimfikry** [katspaugh/wavesurfer.js#320] opened 2014-12-29 20:09 UTC
I'm using wavesurfer in an angularjs project that needs to use two instances at a time in one page. I added the instances in the view using:
```sh
<audioplayer ng-repeat="voice in voices"></audioplayer>
```

while audioplayer is an angularjs directive I've implemented to hold the wavesurfer. and voices will have two elements everytime, even when it change I'll remove one element and add another one.

The major problem with me using Chrome is that it take lots of memory when I do some changes to this array. I used 
```sh
wavesurfer.destroy()
```
and still I've the same problem with too many memory consumed.

**Comment by katspaugh** [comment] 2015-01-03 15:52
It's a known issue. Please see https://github.com/katspaugh/wavesurfer.js/issues/77#issuecomment-34602224 and http://stackoverflow.com/q/19559720/352796.

Closing as a duplicate of #77.

**Closed by katspaugh** 2015-01-03 15:52 UTC
