### ISSUE TITLE
Changing playback rate when using WebAudio backend doesn't retain pitch.

### ISSUE THREAD

**Issue by georgebohnisch** [katspaugh/wavesurfer.js#607] opened 2016-01-06 06:05 UTC
When changing the playback rate on a player initialized with WebAudio, the pitch of the audio changes, however, if initializing the player with MediaElement, the pitch remains unchanged.

**Comment by katspaugh** [comment] 2016-01-06 07:22
Duplicate of #149.

**Closed by katspaugh** 2016-01-06 07:22 UTC
