### ISSUE TITLE
setPlaybackRate has issues

### ISSUE THREAD

**Issue by Caixz** [katspaugh/wavesurfer.js#2324] opened 2021-07-14 07:51 UTC
When the audio frequency is 0.5 or 2 times, the original sound disappears and the female becomes male or machine sound. But I have tried that the multiples provided by the original label < audio / > can remain normal. Can this problem be solved?

**Comment by thijstriemstra** [comment] 2021-07-14 10:33
duplicate of #2296

**Closed by thijstriemstra** 2021-07-14 10:33 UTC
