### ISSUE TITLE
What is the standard bit depth for the PCM data to generate the proper waveform?

### ISSUE THREAD

**Issue by cyb-ahmadh** [katspaugh/wavesurfer.js#839] opened 2016-10-03 09:13 UTC
I'm using the `node-pcm` plugin to generate the PCM data:

```
var pcm = require('pcm');

var min = 1.0;
var max = -1.0;
var arr = [];
var arguments = process.argv[2] ;
pcm.getPcmData(arguments, { stereo: true, sampleRate: 10 },
  function(sample, channel) {
    min = Math.min(min, sample);
    max = Math.max(max, sample);
    console.log(sample);
  },
  function(err, output) {
    if (err)
      throw new Error(err);
      return arr;
  }
);
```
I'm sharing the PCM data generated for the sample media file.

Data generated is:
```
[0,0,0,0,0,0,0,0,0,0,0,0,0,0.00012207403790398877,0.0003051850947599719,0.0005798516800439467,0.0003967406231879635,0.0038453321939756462,0.0045167394024475845,0.00347911008026368,0.00173955504013184,0.002044740134891812,0,0,0.0014038514358958708,0.0036927396465956603,0.0031128879665517136,0.00347911008026368,0.003814813684499649]
```

Through `getPeaks` method of `wavesurfer`:

```
[0.00004548957440420054, -0.000040689697925699875, 0.10731837898492813, -0.1768312305212021, 0.17762556672096252, -0.18214300274848938, 0.0794476717710495, -0.04596053063869476, 0.05181507393717766, -0.04566038399934769, 0.026722609996795654, ...]
```

I guess that's the reason the waveform is not generating properly.

Can you please tell me what is missing ?

**Comment by mspae** [comment] 2016-10-28 14:43
Duplicate of https://github.com/katspaugh/wavesurfer.js/issues/838

**Comment by katspaugh** [comment] 2016-10-30 18:20
Closing as duplicate.

**Closed by katspaugh** 2016-10-30 18:20 UTC
