### ISSUE TITLE
Avoid double resource loading when drawing waveform from a video file

### ISSUE THREAD

**Issue by MartinDelille** [katspaugh/wavesurfer.js#933] opened 2017-01-27 11:06 UTC
I have an application that is displaying the video and the audio waveform. Since WaveSurfer handles video file I load the waveform from it which result in loading the video resource two times.

Is there a way to load the waveform from a video element to avoid this waste of bandwith usage?

**Comment by thijstriemstra** [comment] 2017-01-27 19:14
@MartinDelille can you show some code that explains this issue, I'm not sure if I understand fully.

**Comment by mspae** [comment] 2017-01-27 20:18
If I understand correctly the browser will cache the file at the first request, so no extra bandwidth usage. (Unless you use different URIs or have weird server config) - maybe check the dev tools to see if it is really being downloaded twice.

**Comment by constmoon** [comment] 2019-01-09 02:08
Did you fix this problem? Same with me, the music file is loaded twice. It's not even loaded from cache.
![screenshot](https://user-images.githubusercontent.com/19185307/50871420-d9e81f80-13fe-11e9-89de-b8fd54de31a8.png)

**Comment by MartinDelille** [comment] 2019-01-09 11:53
Sorry I don't use this package anymore.

**Comment by thijstriemstra** [comment] 2019-04-01 00:16
@constmoon do you have some example code to reproduce this?

**Comment by thijstriemstra** [comment] 2019-07-10 21:23
no feedback, closing.

**Closed by thijstriemstra** 2019-07-10 21:23 UTC
Labels: needs-update, question

**Comment by arijitnaskar** [comment] 2022-04-15 09:21
I am facing the same issue. I took the demo code from 
[https://codesandbox.io/s/wavesurfer-react-20-gqvb6?from-embed=&file=/src/index.js]

The problem is, when I am opening the Demo code it's showing just one WaveForm. But From my local project it's loading twice. My Code below

`
import React, {
    useCallback,
    useEffect,
    useRef,
    useState,
    useMemo
  } from "react";

  import { WaveSurfer, WaveForm } from "wavesurfer-react";
  import RegionsPlugin from "wavesurfer.js/dist/plugin/wavesurfer.regions.min";
  
  function WaveSurferUI() {

  
    const plugins = useMemo(() => {
      return [
        {
          plugin: RegionsPlugin,
          options: { dragSelection: true }
        }
      ].filter(Boolean);
    },[]);
  
  
    const [regions, setRegions] = useState([]);
  
    // use regions ref to pass it inside useCallback
    // so it will use always the most fresh version of regions list
    const regionsRef = useRef(regions);
  
    useEffect(() => {
      regionsRef.current = regions;
    }, [regions]);
  
   
  
    const wavesurferRef = useRef();
    const handleWSMount = useCallback(
      (waveSurfer) => {
        if (waveSurfer.markers) {
          waveSurfer.clearMarkers();
        }
  
        wavesurferRef.current = waveSurfer;
  
        if (wavesurferRef.current) {
          wavesurferRef.current.load("/Demo.mp3");
  
          
          wavesurferRef.current.on("ready", () => {
            console.log("WaveSurfer is ready");
          });
  
          wavesurferRef.current.on("loading", (data) => {
            console.log("loading --> ", data);
          });
  
          if (window) {
            window.surferidze = wavesurferRef.current;
          }
        }
      },
      []
    );
  
    const removeLastRegion = useCallback(() => {
      let nextRegions = [...regions];
  
      nextRegions.pop();
  
      setRegions(nextRegions);
    }, [regions]);

    const play = useCallback(() => {
      wavesurferRef.current.playPause();
    }, []);
  
    var i=0;
    return (
      i=i+1,
      console.log(i),
      <div className="waveformui">
        <WaveSurfer plugins={plugins} onMount={handleWSMount}>
        <WaveForm id="waveform" hideCursor cursorColor="transparent"></WaveForm>
      <div id="timeline" />
        </WaveSurfer>
        
          <button onClick={play}>Play / Pause</button>
          <br></br>
          <button onClick={removeLastRegion}>Remove last region</button>
        
      </div>
    );
  }
  export default WaveSurferUI;`

**Comment by Gigamick** [comment] 2023-09-28 23:56
also seeing each audio file being loaded twice:

<img width="1091" alt="Screenshot 2023-09-29 at 00 56 24" src="https://github.com/katspaugh/wavesurfer.js/assets/22120297/fc1f5d56-685d-4a57-88fb-5ffb7b90f8e7">

**Comment by sebbean** [comment] 2025-04-10 02:11
same!
