### ISSUE TITLE
Firefox compounding memory use on page refresh

### ISSUE THREAD

**Issue by mb2140** [katspaugh/wavesurfer.js#313] opened 2014-12-15 04:11 UTC
I'm trying to debug an issue with Firefox & Wavesurfer.  I've noticed that as a user on my website refreshes a page that contains Wavesurfer, memory use in Firefox will slowly continue to creep up.  After enough refreshes & large enough audio files, memory use can become quite large.  I can replicate this on the Wavesurfer.fm homepage:

http://www.wavesurfer.fm/

Open a process explorer and continue hitting F5 on this page, you should see your memory increase after each refresh.  It doesn't look like it is ever released or GC.  Is there another workaround for this?

**Comment by katspaugh** [comment] 2015-01-03 15:53
Duplicate of #77. Please see http://stackoverflow.com/q/19559720/352796 as well.

**Closed by katspaugh** 2015-01-03 15:53 UTC
