### ISSUE TITLE
How to set the current time

### ISSUE THREAD

**Issue by burningding** [katspaugh/wavesurfer.js#1039] opened 2017-03-14 21:39 UTC
Thanks for your awesome job on wavesurfer.js!

I found there's only how to get current time, but there's no way to set current time. I'm not sure if I didn't find it, or we don't have this function right now?
Any ideas?

Thanks,

Shaojin

**Comment by dmongrel** [comment] 2017-03-15 07:51
@burningding The way it's done in the region examples is:

wavesurfer.play(region.start);
wavesurfer.pause();

You can replace region.start with the number of seconds.

**Comment by burningding** [comment] 2017-03-15 17:43
@dmongrel Sorry for the ambiguous narration of question. In my case, I want to set the position of cursor (the current time) to the mid of region (the average between region.start and region.end). How can I achieve this?

Thanks!

**Comment by nelemnaru** [comment] 2017-03-16 01:03
You could also try
`wavesurfer.seekTo(timeToSet / wavesurfer.getDuration())`
where timeToSet is the number of seconds. This shouldn't fire pause and play events.

**Comment by entonbiba** [comment] 2017-03-16 23:07
@burningding you can set it with `seekTo()` method or with `play(); pause()` combined. I'll add a method called `setCurrentTime()` this weekend.

**Comment by burningding** [comment] 2017-03-17 18:44
@entonbiba @nelemnaru Thanks for your help! Looking forward the new version!

**Comment by burningding** [comment] 2017-03-17 19:17
@nelemnaru  @entonbiba I tried to use 

`var sec = wavesurfer.getDuration();
  wavesurfer.seekTo((4/sec)+(12/sec)*.5);`

to set the current time, it works well.

Now I want to drag to add a region and also set the current time to the mid of the region. I tried to add the code above to the event "region-update-end", it's true that the cursor will be set to the mid when "region-update-end" is fired. However,  it seems that another mouse event is also fired, so at last, the cursor will be set to the place where I release the mouse. I also tried to use stopPropagation as well as stopImmediatePropagation in "region-update-end" event, but it doesn't work. Any idea on it?

Thanks!

**Comment by entonbiba** [comment] 2017-03-17 22:34
@burningding so when you drag the region, you want it to set the play time in the middle or ?
The event `region-update-end` should work, can you post a sample on codepen?

**Comment by nelemnaru** [comment] 2017-03-17 23:19
I have a similar problem trying to play a region on double click, and stopPropagation doesn't help. It starts playing the region, but the cursor ends up moving to where I clicked. Currently, I'm using a workaround by using a setTimeout delay of 0.
`wavesurfer.on('region-dblclick', function (region, e) {
	e.stopPropagation();

	setTimeout(function(){
		region.play();
	}, 0);
});`
You could try setting a 0 timeout on your code until the issue is solved.

**Comment by entonbiba** [comment] 2017-04-03 16:22
@nelemnaru you can use `e.stopImmediatePropagation();` instead,

```
wavesurfer.on('region-dblclick', function (region, e) {
    e.stopImmediatePropagation();
    region.play();
});
```

**Comment by nelemnaru** [comment] 2017-04-03 23:10
@entonbiba I tried your suggestion to no avail. The region still begins playing from where I double-clicked instead of region start. (Don't know if it matters, but I'm using Firefox.)

**Comment by entonbiba** [comment] 2017-04-07 22:25
@nelemnaru updated, just remove the `region.play();' part from the code

```
wavesurfer.on('region-dblclick', function (region, e) {
    e.stopImmediatePropagation();
    // code here
});
```

**Closed** 2017-09-03 13:15 UTC
Labels: enhancement, question
