### ISSUE TITLE
 problems in chrom

### ISSUE THREAD

**Issue by janjon** [katspaugh/wavesurfer.js#903] opened 2016-12-27 07:47 UTC
demo address 'https://wavesurfer-js.org/example/audio-element/'

the state of play: I click on the fallback position, play sound right, but the cursor will return to the original position.
Pause status: no problem.

also hope to reply, thank!

**Comment by katspaugh** [comment] 2016-12-27 09:23
Duplicate of #900.

**Closed by katspaugh** 2016-12-27 09:23 UTC
